### ISSUE TITLE
API access for "scheduled_charging_start_time"?

### ISSUE THREAD

**Issue by Alchete** [timdorr/tesla-api#102]
As the title says, is there API access for the scheduled_charging_start_time field?  I would love to be able to set this programmatically.

Thank you for your work on this project.

**Comment by timdorr** [comment]
There isn't currently a way to schedule a charge. You can start and stop charging if the car is plugged in, which you can call on a schedule from another system (cron or something similar).

**Comment by Jugglenaut** [comment]
A workaround is to setup a server to kickoff a charge using crontab. Downside, is you need to know your way around a Linux system.

**Comment by brianflex** [comment]
You could try an app for managing charging via scheduling.  IE, look at https://flexcharging.com.  App works on iOS and Android.
