### ISSUE TITLE
Any info about API for heated seats & steering wheel?

### ISSUE THREAD

**Issue by MoonScript** [timdorr/tesla-api#103]
With latest car software version `2018.48.12`, you can now turn on individual heated seats or the heated steering wheel from the mobile app.  So there must be an API that we can call to do the same, right?

https://electrek.co/2018/12/21/tesla-mobile-app-update-seat-heating-service-scheduling/

**Comment by timdorr** [comment]
Leaving this open until I actually do it or someone submits a PR.

**Comment by jor-dan** [comment]
I've submitted #106 to deal with seat heaters. Unfortunately my car does not have a heated steering wheel so I can't test that.
