### ISSUE TITLE
What happened to console view on previous site?

### ISSUE THREAD

**Issue by allante2** [timdorr/tesla-api#110]
I know that the Tim Dorr apiary site has moved to a new site, but where is the console view that enabled you to type in code to retrieve, for example, access tokens?  I see the documentation in the new site, but where is the console view?  How and where do I enter the parameters?  I can't simply do it in a browser window.

Please Help!

**Comment by timdorr** [comment]
There is no console view. I would have disabled it if I could have. The Apiary Blueprint format isn't able to properly model the Tesla API, so it was an improper mock of their service.

**Comment by jtamplin** [comment]
It's easy enough to just use curl from the command line.
