### ISSUE TITLE
404 Error when attempting to query the energy_sites /status URL for solar production

### ISSUE THREAD

**Issue by elijah286** [timdorr/tesla-api#112]
I get a 404 error when attempting to query the /status URL - is this still a valid path? Conversely, live_status appears to be working

**Comment by timdorr** [comment]
In general, they don't remove APIs. You can always see what's in the endpoints file: https://tesla-api.timdorr.com/miscellaneous/endpoints

It may matter if you're doing a GET vs a POST. It could also be an error on their end or some sort of internal change.
