### ISSUE TITLE
Does this go through the internet? Or directly from the car?

### ISSUE THREAD

**Issue by trusktr** [timdorr/tesla-api#118]
I'm curious to know if we read the data from the JSON API from the net? Or do we read it directly from a service running on the car?

If it is internet, seems like that'd have too much opportunity for high latency.

What I'd like to do is read the `power` and use that to dynamically adjust audio volume of a device.

**Comment by timdorr** [comment]
Parts of the API only hit Tesla's servers, but for the most part they are proxying requests through their internal VPN straight to the car. Certain API responses change based on the firmware of the car. 

Latency is certainly fairly high, but not so much that you can't use it for Summon/AutoPark.

You could also use the CAN bus from within the car itself. You can definitely get those readings directly from the car, without modification (no ripping the dash apart). That can be a backup option if the API doesn't respond quickly enough.
