### ISSUE TITLE
Add Sentry Mode documentation

### ISSUE THREAD

**Issue by josephaVMW** [timdorr/tesla-api#119]
The path for Sentry Mode is `command/set_sentry_mode`. It uses the _on_ parameter just like Valet Mode - however, I noticed that it will only enable if you supply the parameter as part of a JSON body. It will not work as query params - it will say success but nothing will happen on the car.

I've personally tested this on my 2019.5.15 Model 3, but if you'd like another source, the [teslajs](https://github.com/mseminatore/TeslaJS/blob/master/teslajs.js) library makes explicit reference to this endpoint in its _setSentryMode_ function in the main **teslajs.js** file.

--Aaron

**Comment by jor-dan** [comment]
I've also confirmed that this works so I opened a pull (#120)
