### ISSUE TITLE
Can get token and Vehicles but 404 on everything else

### ISSUE THREAD

**Issue by JulienParis86** [timdorr/tesla-api#121]
First of all thanks for this great work.

I tried on my new Model 3. I successfully get a token and then get response for “Vehicles” request, but all other requests are returning 404.

I tried both with id and vehicle_id without success.

Anyone with the same issue ?

**Comment by bowyern** [comment]
This is happening to me as well. I had it working ~48 hours ago, but it doesn't seem to work now.

Not sure if this is relevant, but the iOS app was last updated on 2/22.

**Comment by bowyern** [comment]
I woke up my Tesla with the iOS app, and now the endpoint is responding with data as it was yesterday.

@JulienParis86 Before waking my Tesla its status was "asleep" on the vehicle list. Its "online" now. Does that make a difference for you?

**Comment by timdorr** [comment]
Yes, most endpoints require the car to be woken up first.

**Comment by JulienParis86** [comment]
Thanks @bowyern.

In fact « /api/1/vehicles » works fine but for example « /api/1/vehicles/{id} » with the id of the vehicle returns a 404.

I tried online and asleep and it’s the same.

**Comment by JulienParis86** [comment]
Ok now using the id_s, it’s ok !

**Comment by kjyam98** [comment]
Ah waking up my car did the trick - was running into the same issue...thought I was messing something up in Postman. @timdorr thanks for putting together the how-to guide - you rock!!
