### ISSUE TITLE
Suddenly error viewing vehicles

### ISSUE THREAD

**Issue by thomasstr** [timdorr/tesla-api#124]
Got this error from the example;

`/Users/thomas/.rvm/gems/ruby-2.4.4/gems/tesla_api-1.4.1/lib/tesla_api/client.rb:57:in vehicles': undefined method `map' for nil:NilClass (NoMethodError) from /Users/thomas/Development/Ruby/tesla.rb:12:in `<main>'`

**Comment by timdorr** [comment]
Your session may have expired or you have the wrong credentials. Make sure you're using the latest client ID and secret too. Unfortunately, unless there's something specifically wrong with the code, I can't fix anything related to Tesla's API service.

**Comment by thomasstr** [comment]
The same code worked yesterday. Using the latest credentials from your website. How can the session be renewd?

`require 'tesla_api'
TESLA_CLIENT_ID="81527cff06843c8634fdc09e8ac0abefb46ac849f38fe1e431c2ef2106796384"
TESLA_CLIENT_SECRET="c7257eb71a564034f9419ee651c7d0e5f7aa6bfbd18bafb5c5c033b093bb2fa3"
TESLA_EMAIL="MY_EMAIL"
TESLA_PASS="MY_PASS"

tesla_api = TeslaApi::Client.new(TESLA_EMAIL, TESLA_CLIENT_ID, TESLA_CLIENT_SECRET)
tesla_api.login!(TESLA_PASS) # Or tesla_api.token = token if you have an existing token.
model_s = tesla_api.vehicles.first # => <TeslaApi::Vehicle>

charge_state = model_s.charge_state
puts "Your Model S is #{charge_state["charging_state"]} " +
     "with a SOC of #{charge_state["battery_level"]}% " + 
     "and an estimate range of #{charge_state["est_battery_range"]} miles"`

**Comment by timdorr** [comment]
It's got to be your login credentials. Make sure you have them right. This works for me:

```rb
irb(main):004:0> tesla_api = TeslaApi::Client.new("timdorr@timdorr.com", "81527cff06843c8634fdc09e8ac0abefb46ac849f38fe1e431c2ef2106796384", "c7257eb71a564034f9419ee651c7d0e5f7aa6bfbd18bafb5c5c033b093bb2fa3")
=> #<TeslaApi::Client:0x00007fbe3332bf10 @email="timdorr@timdorr.com", @client_id="81527cff06843c8634fdc09e8ac0abefb46ac849f38fe1e431c2ef2106796384", @client_secret="c7257eb71a564034f9419ee651c7d0e5f7aa6bfbd18bafb5c5c033b093bb2fa3">
irb(main):005:0> tesla_api.login!("<snip>")
=> "65d...snipped"
irb(main):006:0> tesla_api.vehicles
=> [#<TeslaApi::Vehicle:0x00007fbe34179bf8 @api=TeslaApi::Client, @email="timdorr@timdorr.com", @id=19298251174317440, @vehicle={"id"=>19298251174317440, "vehicle_id"=>1817902171, "vin"=>"5YJSA1E41GF167745", "display_name"=>"Nikola 2.0", "option_codes"=>"MDLS,RENA,AF02,APF1,APH2,APPB,AU01,BC0R,BP00,BR00,BS00,CDM0,CH05,PBCW,CW00,DCF0,DRLH,DSH7,DV4W,FG02,FR04,HP00,IDBA,IX01,LP01,ME02,MI01,PF01,PI01,PK00,PS01,PX00,PX4D,QTVB,RFP2,SC01,SP00,SR01,SU01,TM00,TP03,TR00,UTAB,WTAS,X001,X003,X007,X011,X013,X021,X024,X027,X028,X031,X037,X040,X044,YFFC,COUS", "color"=>nil, "tokens"=>["<snip>", "<snip>"], "state"=>"online", "in_service"=>false, "id_s"=>"19298251174317440", "calendar_enabled"=>true, "api_version"=>6, "backseat_token"=>nil, "backseat_token_updated_at"=>nil}>]
```
