### ISSUE TITLE
Model 3 options codes are wrong.

### ISSUE THREAD

**Issue by RSickenberg** [timdorr/tesla-api#126]
Hello, when I hit the endpoint `api/1/vehicles`, I get those options codes 

```
AD15,MDL3,PBSB,RENA,BT37,ID3W,RF3G,S3PB,DRLH,DV2W,W39B,APF0,COUS,BC3B,CH07,PC30,FC3P,FG31,GLFR,HL31,HM31,IL31,LTPB,MR31,FM3B,RS3H,SA3P,STCP,SC04,SU3C,T3CA,TW00,TM00,UT3P,WR00,AU3P,APH3,AF00,ZCST,MI00,CDM0
```

Which are wrongs, I have the 18-inch red.
I guess the fault is on Tesla side, but the iOS / Android app are right, can you find a solution?
I tried to decompile the APK but not found something relevant.

**Comment by timdorr** [comment]
Tesla controls that info, so it would be on their end to fix it. It may also be incorrect documentation on our end, but we'd need to see something specific here to know that's the case.

In general, they've moved away from option codes for determining the car's metadata towards more specific endpoints. `vehicle_config` in particular is one they use now. It's easier to read and make sense of.

**Comment by boekabart** [comment]
Broken for many many cars now, I get the same exact string for my X

**Comment by lyceel** [comment]
My option codes were fine until I got the FSD/MCU2 hardware upgrade.  Now, my blue 2017 Model S 75D with free unlimited supercharging has apparently turned into a black Model 3 with paid supercharging :-O
