### ISSUE TITLE
Sentry mode

### ISSUE THREAD

**Issue by bkbonner** [timdorr/tesla-api#133]
Is there an API for sentry mode?   It looks like there is, but I can't navigate to it.  I'd like to be able to do this remotely.

**Comment by timdorr** [comment]
Looks like it wasn't added to the sidebar menu, so you couldn't see it. But it's here: https://tesla-api.timdorr.com/vehicle/commands/sentrymode

**Comment by bkbonner** [comment]
Thank you.

**Comment by kevykk** [comment]
Were you able to get this to work? I can disable sentry mode by just calling the endpoint without any parameters but when I set the URL query params to on=true, I am unable to get sentry to activate. Thanks!

**Comment by bkbonner** [comment]
shortly after this was added..they included it in the app.   I haven't done anything else with it.

**Comment by kevykk** [comment]
Thanks. Got it to work. One of those obscure bugs where lines of good code were conflicting with other lines of good code to produce bad code. 🙂

**Comment by bkbonner** [comment]
lol

**Comment by bkbonner** [comment]
glad you got it working.

**Comment by kevykk** [comment]
Do you have some way to see the streams of data going back and forth from the Tesla app itself?
