### ISSUE TITLE
Update documentation regarding IDs

### ISSUE THREAD

**Issue by clauderobi** [timdorr/tesla-api#139]
I was under the impression that id, or id_s, was immutable. In other words, equivalent to the VIN. So I based my main DB key on this id. Well, it turn out that it is mutable!!! For one of my cars, the id is now different. 

I guess I will have to change by DB scheme and use the VIN after all....

An additional piece of information: few days ago, the car in question disappeared from the APP. And reappeared. after few hours. I guess the app got confused too with the change of ID!!!!!!  

I am just suggesting to add this information into the doc.

**Comment by timdorr** [comment]
I would assume so too, but something special must have happened to your car. I know they sync data from external systems (Salesforce, in particular) to create the entry for the car in the app. Something might have gotten messed up on their end and they fixed it for you. 

If you want to make a PR to add a note, please feel free!

**Comment by scootklein** [comment]
can confirm this just happened to me! seems like it was related to the issues Tesla had with their app this week (and probably why the "log out and log back in" advice worked)
