### ISSUE TITLE
What does use_range_badging mean?

### ISSUE THREAD

**Issue by rawmean** [timdorr/tesla-api#145]
It appears in `vehicle_config`

```   
response =     {
        "can_accept_navigation_requests" = 1;
        "can_actuate_trunks" = 1;
        "car_special_type" = base;
        "car_type" = model3;
        "charge_port_type" = US;
        "eu_vehicle" = 0;
        "exterior_color" = RedMulticoat;
        "has_air_suspension" = 0;
        "has_ludicrous_mode" = 0;
        "key_version" = 2;
        "motorized_charge_port" = 1;
        plg = 0;
        "rear_seat_heaters" = 1;
        "rear_seat_type" = "<null>";
        rhd = 0;
        "roof_color" = Glass;
        "seat_type" = "<null>";
        "spoiler_type" = None;
        "sun_roof_installed" = "<null>";
        "third_row_seats" = "<invalid>";
        timestamp = 1566516169069;
        "use_range_badging" = 1;
        "wheel_type" = Pinwheel18;
```

**Comment by timdorr** [comment]
My best guess is it's for cars produced after they did away with the battery size badging. It's the Long Range and Performance versions now, so they show up differently in the UI.

**Comment by rawmean** [comment]
I get the 'use_range_badging' field for my Model 3 (LR AWD) which doesn't have a battery badge ( just says Dual Motor).
My Model S 75D 2018 doesn't include this field. Instead it has the `trim_badging`.

 'use_range_badging' should be added to your wonderful and incredibly useful API documentation.

**Comment by timdorr** [comment]
By all means, feel free to submit a PR. It's simple markdown.

**Comment by oliverkurth** [comment]
Has this been figured out? Just started playing with the API and now I have the same question. FWIW, it's `true` for a 2019 SR+, no options, delivered in August.
