### ISSUE TITLE
OAuth authentication code grants?

### ISSUE THREAD

**Issue by brianflex** [timdorr/tesla-api#147]
Is it possible for a third party app to get an access token that allows lesser permission to a car?  IE, I want to check the battery status but I don't want to start the car.
It seems like an OAuth 2.0 password grant works, but gives me full access.  It may not be the best way to do this.

**Comment by timdorr** [comment]
Nope, there is no scoping on Tesla's API.

**Comment by brianflex** [comment]
Ok.  Is there any more user-friendly way to log in than just using a password?

**Comment by timdorr** [comment]
Nope, that's the only way currently. The API is built for the app, not our general use.

**Comment by Lizzard44** [comment]
I do that myself in the service that uses the API.
Of course, this is only possible if you do it yourself or trust the operator.
