### ISSUE TITLE
unexpected "offline" state

### ISSUE THREAD

**Issue by joergmehring** [timdorr/tesla-api#158]
Hi Tim, 
thank you for the wonderful work of reverse engeneering the Tesla API.

My Model 3 sometimes reports "offline" in the state field of the vehicles query. Then, it's not possible to wake it up with the wake_up command. Therefore I cannot climate my car automatically. (Yes, it's cold here in Germany now.) On the other side, using the Tesla-App wakes up the car normal. Do you have any idea which command helps? The Tesla-App seens to do somthing more.

Thank you in advance.
Jörg Mehring

**Comment by timdorr** [comment]
Does the `wake_up` fail? You may need to give it some time to turn on after sending that command, as the system needs to boot up (which might be a deeper sleep mode if it's overnight)

**Comment by joergmehring** [comment]
Hi,

> Does the wake_up fail? You may need to give it some time to turn on after sending that command, as the system needs to boot up (which might be a deeper sleep mode if it's overnight)

yes, the wake_up command fails. My delay after wake_up is 10 seconds.

I’ve released the script here: https://github.com/joergmehring/TeslaClimate <https://github.com/joergmehring/TeslaClimate>
Best regards
Jörg

**Comment by karekaa** [comment]
Even the official App from Tesla, will sometimes «turn the waiting spinner» for quite a long time, and without actually meassure it, I'll guess it is sometimes more than 10 seconds?
It is not wrong for the API to give back the control fast, while the USER of the API, should preferably don something like this pseudocode:
tries=0;
while (wake_up.status == "offline") {
    print "Waiting for Tesla to wake up ..."
    sleep 2 seconds;
    tries++;
    if (tries > 30) {
        print "Check your car, failed after trying for 1 minute";
    }
}
if (tries > 0) {
    log (to_my_log_file, "At $date_time, when temperature was $temp, the Tesla neede $tries*2 seconds to wake up";
}

I think that a freezing cold Tesla might well have at least 1 minute of chance.  You might as well make some logging as suggested above, and later come back here and give some insight in typical waiting times to expect for different temperatures?
If all this work well, this not a bug/issue, but more a feature, to let the programmer keep the user informed about some delay.

**Comment by timdorr** [comment]
Yeah, sorry for not responding earlier, but the car definitely needs more than 10 seconds to boot out of deep sleep mode.
