### ISSUE TITLE
Error 401, cannot get access token

### ISSUE THREAD

**Issue by rossman729** [timdorr/tesla-api#160]
With the following script I am receiving: 
{"response":"undefined_method_`strip'_for_nil:nilclass"}

What am I doing wrong? This is my first time working with the Tesla API and after following the unofficial API authentication document I cannot seem to get this to work. Please help :-)
Note: I am using the actual email and password in place for the "XXX" in the code.

```javascript
const request = require("request");

var base_url = 'https://owner-api.teslamotors.com'
var options = { 
                url: base_url + '/oauth/token?grant_type=password',
                method: 'POST',
                port: 443,
                'Content-Type': 'application/json',
                headers: { 
                    'grant_type': 'password',
                    'client_id': '81527cff06843c8634fdc09e8ac0abefb46ac849f38fe1e431c2ef2106796384',
                    'client_secret': 'c7257eb71a564034f9419ee651c7d0e5f7aa6bfbd18bafb5c5c033b093bb2fa3',
                    'email': 'XXXXXX',
                    'password': 'XXXXXX',
                    'User-Agent': '007', // Forums have suggested this
                         } 
              };

request(options, function (error, response, body, status) { //body and response are garbage
    if (error) {
        console.log(error)
        throw new Error(error);
    }
    var my_obj = body
    console.log(my_obj)
});
```

**Comment by timdorr** [comment]
Except for the User Agent, those aren't headers. Those all go in the POST body.

**Comment by rossman729** [comment]
Thanks for the reply, so they just have to go above the headers, in as parameters for options? When I do that it gives me the same response.

**Comment by timdorr** [comment]
I'm not sure of the specifics of that library, as I don't use it myself. Just put them in the POST body.

**Comment by rossman729** [comment]
Thank you so much, I figured it out after that.
