### ISSUE TITLE
How can I get actuate_trunks open status?

### ISSUE THREAD

**Issue by mrgaolei** [timdorr/tesla-api#163]
I can only open or close actuate trunks,
But how can I get the open status?
Official App can do this.

**Comment by karekaa** [comment]
I have made pull request to update the docs/vehicle/state/vehiclestate.md with the right status to look for if trunk is open (rt == 32, closed == 0) or frunk (ft == 16, closed == 0).  The «problem» is these kind of short «cryptic» names.

**Comment by karekaa** [comment]
Hi @mrgaolei 

This issue has been solved and published as described above. You will have that documentation into your own local clone, if you perform a new «git pull».

I've been looking for how to close this issue, but I might not have privileges for that ...

Good luck with your usage of this great API made by @timdorr 

Sincerely
Kjell Arne Rekaa

**Comment by mrgaolei** [comment]
Thanks
