### ISSUE TITLE
Why option_codes all same?

### ISSUE THREAD

**Issue by mrgaolei** [timdorr/tesla-api#168]
I found that all car's option_codes all same as:
```
"option_codes": "AD15,MDL3,PBSB,RENA,BT37,ID3W,RF3G,S3PB,DRLH,DV2W,W39B,APF0,COUS,BC3B,CH07,PC30,FC3P,FG31,GLFR,HL31,HM31,IL31,LTPB,MR31,FM3B,RS3H,SA3P,STCP,SC04,SU3C,T3CA,TW00,TM00,UT3P,WR00,AU3P,APH3,AF00,ZCST,MI00,CDM0",
```
In API: https://owner-api.teslamotors.com/api/1/vehicles with theirs token
I test 40+ different cars.

**Comment by timdorr** [comment]
I don't believe they're using them for any vehicle anymore. I have noticed the same. We should probably drop the option codes page as a result. They've moved to vehicle_state fields instead.

**Comment by mrgaolei** [comment]
> I don't believe they're using them for any vehicle anymore. I have noticed the same. We should probably drop the option codes page as a result. They've moved to vehicle_state fields instead.

How can I know which car is FSD HW 2.5 or 3.0?

**Comment by corsair** [comment]
@mrgaolei There is nothing within the API that can be used to help determine whether a vehicle has HW2.5 or 3 programmatically. The only differentiators currently are if a vehicle can view cones (or other visualizations) that are currently flagged for HW3 only.

**Comment by davesalomon** [comment]
+1 to either removing the page, or at least calling out that Option Codes are deprecated and shouldn't be used. Definitely just spent half a day trying to figure out why a Model S is being reported as a Model 3 🤦‍♂.
