### ISSUE TITLE
Undocumented option codes data

### ISSUE THREAD

**Issue by robbat2** [timdorr/tesla-api#169]
Model3 on loan here, and I see it's got a few option codes that aren't in `optioncodes.md`. Not sure what they are yet, but wanted to list them in the meantime.

- `SA3P`
- `T3CA`
- `ZCST`

Complete set for this vehicle:
`AD15,MDL3,PBSB,RENA,BT37,ID3W,RF3G,S3PB,DRLH,DV2W,W39B,APF0,COUS,BC3B,CH07,PC30,FC3P,FG31,GLFR,HL31,HM31,IL31,LTPB,MR31,FM3B,RS3H,SA3P,STCP,SC04,SU3C,T3CA,TW00,TM00,UT3P,WR00,AU3P,APH3,AF00,ZCST,MI00,CDM0`

**Comment by timdorr** [comment]
The API has been returning the same option codes for all vehicles recently, so they appear to be deprecated. I don't think we need to document them anymore.

If you do figure them out, feel free to make a PR to add them. Who knows, maybe Tesla will fix them again someday.
