### ISSUE TITLE
Request Timeout

### ISSUE THREAD

**Issue by JpMontgomery** [timdorr/tesla-api#173]
Hello,

Has anyone else been having this issue? It works some of the time but about half the time it gives me a request timeout when I try to access data.

urllib.error.HTTPError: HTTP Error 408: Request Timeout

Does anyone know anything I can do to fix this?

Thank you,
Jacob

**Comment by timdorr** [comment]
That's whenever Tesla's servers cannot reach the car. Happens all the time in my experience. You should have retry handling in your code to deal with it, as you should expect it to happen.
