### ISSUE TITLE
We're sorry, but something went wrong (500)

### ISSUE THREAD

**Issue by WeiQiZhang** [timdorr/tesla-api#176]
POST URL:https://owner-api.teslamotors.com/oauth/token
body: {
grant_type:password
client_id:81527cff06843c8634fdc09e8ac0abefb46ac849f38fe1e431c2ef2106796384
client_secret:c7257eb71a564034f9419ee651c7d0e5f7aa6​​bfbd18bafb5c5c033b093bb2fa3
email:xxxx
password:xxxx
}

**Comment by WeiQiZhang** [comment]
hello，When I input error email or password, it response { "response": "authorization_required_for_txid_`4f26dda0dbdddb148f566cb0cfc7c1ef`" }. But the email and password is true and it response "We're sorry, but something went wrong".

**Comment by timdorr** [comment]
Make sure you're sending the right headers too.
