### ISSUE TITLE
Charge port door open is 404?

### ISSUE THREAD

**Issue by nmg196** [timdorr/tesla-api#177]
I want to unlock the charge port when I open my garage door. But the API command seems to be 404 not found:

POST
https://owner-api.teslamotors.com/api/1/vehicles/:myid/command/charge_port_door_open

Anyone know what the correct command is?

**Comment by timdorr** [comment]
That is definitely the right command. I just ran it successfully. Make sure you have the right vehicle id (the `id` or `id_s` field).

**Comment by nmg196** [comment]
Yeah my vehicle ID is taken straight from the API.  Strange how I can't use this command on my account when the other commands work OK :(

**Comment by nmg196** [comment]
I can set the air-con with the same format URL.

**Comment by timdorr** [comment]
What version of the car software do you have? Also, do you have a motorized charge port?

**Comment by nmg196** [comment]
I have a Model 3 with motorised charge port which I can open OK from Tesla app and 3rd party apps like "Stats".

**Comment by nmg196** [comment]
OK I've managed to spy on the traffic from the Stats app and I can see now I was using the wrong ID. Strange how some commands work with the vehicle_id, but some require the "id"
