### ISSUE TITLE
Wake up

### ISSUE THREAD

**Issue by Dreamsorcerer** [timdorr/tesla-api#183]
I was just wondering if anyone had information on how the wake up should be handled, or how the official Tesla app is handling it?

If I call the wake_up API, the response says that the car state is still offline, and immediately calling another command results in a "vehicle unavailable" error. It seems that the wake up happens shortly after the API call was successful, i.e. it doesn't block on the wake up process and gives no information on whether it's successful or not.

Perhaps just adding a 1 second delay after calling the wake_up API will be good enough, but it doesn't sound very robust. Or, maybe just polling the vehicle endpoint until the state changes is a better option.

Any thoughts on the best way to handle this would be great.

**Comment by LelandSindt** [comment]
I can't say that this is the best way or the right way. At a minimum I should have a timeout in this loop.

https://github.com/LelandSindt/iftttGateway/blob/15eb9239782e97713eb37398b81cb6a7dded205f/main.go#L114

**Comment by jonasman** [comment]
What i do in my app is to call wake up for 3 times with some delay until the car says “online”. if it fails the app shows “car didnt wake up”

Joao

**Comment by Dreamsorcerer** [comment]
Thanks for the help. I've got something similar working now.

I've made a PR to include that information in the docs as well.

**Comment by LelandSindt** [comment]
That was embarassing enough that I ~~fixed it~~ made it better :smile: 

https://github.com/LelandSindt/iftttGateway/blob/4d3ce30dbd0631ec38374201c22248a9dd1bfa59/main.go#L115
