### ISSUE TITLE
Valet Mode Documentation Update

### ISSUE THREAD

**Issue by derekteay** [timdorr/tesla-api#186]
I couldn't think of a better way to rewrite your documentation, so I'll leave that to you! I just wanted to provide some info on the Valet Mode API, as I think it changed a little bit since the docs were written. I have a Model 3 Performance with 2020.12.5 installed, for what it's worth.

`password` isn't required to turn on Valet Mode with a previous pin, which is documented properly. However, a pin isn't required to disable Valet Mode from the API, which is consistent with the current version of the app but not consistent with the docs - `true to activate, false to deactivate. Must include previous PIN if deactivating.` You do still need to provide a pin when disabling Valet Mode it from the car's screen, but not the API. A noteworthy distinction for the docs, I think.

Also, it might be best to note in the docs that clearing the pin from the API works as expected, but if you use the API to clear the pin and then turn on Valet ModeI without providing a pin (which you can't do from the app), it will still activate Valet Mode. But, when you try to deactivate Valet Mode from the car's screen, you won't be able to enter a valid pin because you cleared it from the API, so to disable Valet Mode, you have to either:

1. Sign into your Tesla account from the car's screen

    or

2. Use the app to turn off Valet Mode

    or

3. Use the API to turn off Valet Mode and then clear the Valet Mode pin, turn on Valet Mode with the new pin, turn off Valet Mode to set a new PIN.

Thanks for all your work on this API, by the way. I'm creating something with Node-RED, but it's all based on this API. If you want more info about it, let me know!

**Comment by timdorr** [comment]
They're all in plain markdown format. The Valet Mode section is here: https://github.com/timdorr/tesla-api/blob/master/docs/vehicle/commands/valet.md

Feel free to make a PR to submit any changes you'd like to see.

**Comment by derekteay** [comment]
Oh, I know where they are and was going to submit a PR but I just couldn't think how to eloquently word this, so I thought maybe you'd like to write it up so it fits in with the rest of the API. I'll send in a PR.

**Comment by derekteay** [comment]
PR created: https://github.com/timdorr/tesla-api/pull/187
