### ISSUE TITLE
How to close Model X window?

### ISSUE THREAD

**Issue by mrgaolei** [timdorr/tesla-api#189]
https://owner-api.teslamotors.com/api/1/vehicles/{remote_id}/command/window_control

I POST:
```json
{
"command": "close"
}
```

Response:
```json
{
  "response": {
    "reason": "too_far_from_vehicle",
    "result": false
  }
}
```

I tried:
```json
{
"command": "close",
"latitude": 39.871517,
"longitude": 116.63881
}
```
Response too_far_from_vehicle too.

But I seen some app can close model X window.

**Comment by vercorsio** [comment]
Helo Mr Gaolei,

You probably need to send latitude and longitude that correspond to where
your car is.
Without that, the windows will not entirely close.
Stay safe

Nicolas
http://tesla.jeedom.free.fr

**Comment by mrgaolei** [comment]
> Helo Mr Gaolei, You probably need to send latitude and longitude that correspond to where your car is. Without that, the windows will not entirely close. Stay safe Nicolas http://tesla.jeedom.free.fr
> […](#)

I send latitude and longitude same as the car's, `too_far_from_vehicle` too.
And Tesla official app also can't close Model X's window.
But I seen third party app can close.
So can you close Model X's window remote?

**Comment by timdorr** [comment]
Don't make it exact, just close to it.
