### ISSUE TITLE
wake_up not fully waking up

### ISSUE THREAD

**Issue by marcone** [timdorr/tesla-api#190]
It seems the wake_up command doesn't wake up the car in the same way that the Tesla app does: when I open the Tesla app, the USB ports in my model S become powered, but when I use the wake_up command they don't.
Is there any way to figure out what the Tesla app does differently, and add support for it in tesla-api?

**Comment by timdorr** [comment]
The API documented here is the exact same API used by the app. That's where the documentation comes from. 

You may need to call the `vehicle_data` endpoint to get the car to fully wake up. That will request from a number of subsystems, all of which need to be online to answer that request.

**Comment by marcone** [comment]
I've tried `vehicle_data` and many others, and none seem to wake up the car the same as the app does. If you're certain that the APIs documented here are the *only* ways that the app interacts with the car, then I suppose that could mean the API needs to be called in a specific way (e.g. a specific order of commands), hence my question about whether it's possible to figure out what the Tesla app actually does.

**Comment by coleged** [comment]
This shouldn't be closed. This issue is well documented in many forums. It seems the app is doing more than simply posting a wake_up. I have tried all sorts of combinations of calls, delays, waits, repeats and cant wake the car. Tickle the app and it wakes; I can then interact over the API.

**Comment by marcone** [comment]
I looked into this a bit more, and it appears that it's the streaming API endpoint that's actually waking the car up.

**Comment by coleged** [comment]
Can you provide a few details. i.e. endpoint to tickle and how. I'm brewing my own code and this is my first time with REST.

**Comment by marcone** [comment]
@coleged the streaming API is WebSocket, which I guess is technically not REST.
See https://github.com/timdorr/tesla-api/blob/master/lib/tesla_api/stream.rb

**Comment by coleged** [comment]
OK. Less familiar with WebSocket than REST, but now have a ws client class running and can connect to Tesla. With absolutely no Ruby, and in the absence of any comments or documentation on the ws protocol, I'm finding it hard to unpick anything from the code here.  Can you briefly detail the strings I should send/expect to get, or point me in the right direction.
