### ISSUE TITLE
Image of the car?

### ISSUE THREAD

**Issue by MikeBishop** [timdorr/tesla-api#193]
The app is clearly able to generate an image of the car.  From some inspection on the Tesla web site, it looks like it's using a URL like....

    https://static-assets.tesla.com/v1/compositor/?model=m3&view=STUD_3QTR&size=1440&options=DV4W,IN3PW,COL3-PPMR,W38B,MT303&bkba_opt=1&context=design_studio_2

However, since the options codes in the API have been frozen/deprecated, clearly they're getting the list of options from someplace else.  It's possible they're just translating things off data_request/vehicle_config, in which case the translation database must be a pain to manage.  Any chance to retrieve that translation code?  Can you tell if the app using the same approach to get the vehicle image?

**Comment by davidhodge** [comment]
I don't know what the official Tesla app is doing, but for Nikola I decided that I have had to maintain a mapping from known vehicle_config varieties to option codes. Would love to know if there's a better way to do it, but have yet to find it.

**Comment by kevinelliott** [comment]
@davidhodge How are you able to detect Model 3 Performance in Nikola from the vehicle_config? I'm not seeing anything obviously different than a standard Model 3.

**Comment by Urkman** [comment]
Why is this closed? I think this still a valid question...

**Comment by itsMeDavidV** [comment]
Yeah I also don't necessarily think this should be closed. There is a valid approach to getting vehicle option codes. We should work to figure this out.

**Comment by timdorr** [comment]
This isn't part of the API. The options codes haven't worked properly for years. However one gets a picture of their car using this image generation service isn't going to be done through this API, hence I closed this out.

**Comment by itsMeDavidV** [comment]
Hmm I don't think we can completely rule out that the API won't give us access to option codes or a vehicle image.

Just some from [endpoints](https://github.com/timdorr/tesla-api/blob/master/ownerapi_endpoints.json):

`"VEHICLE_DETAILS_ASSETS_REQUEST_V2": {
    "TYPE": "GET",
    "URI": "bff/v2/mobile-app/ownership/vehicle-details-assets/v2",
    "AUTH": true
  },
"OWNERSHIP_VEHICLE_SPECS_REQUEST": {
    "TYPE": "GET",
    "URI": "bff/v2/mobile-app/ownership/vehicle-details",
    "AUTH": true
  },
  "OWNERSHIP_RESERVATION_DETAILS_REQUEST": {
    "TYPE": "GET",
    "URI": "bff/v2/mobile-app/ownership/reservation-details/{rn}",
    "AUTH": true
  },
"VEHICLE_ORDER_LIST": {
    "TYPE": "GET",
    "URI": "api/1/users/orders",
    "AUTH": true
  }, ...`
  
There's something to be said for if a token intended for owner-api use will allow access to these, however I think this is def worth figuring out. Best case, it does.

**Comment by timdorr** [comment]
The API gives you option codes, but those have been the same option codes (regardless of the actual car configuration) for any vehicles produced in the last few years. They're not the same ones provided by the Tesla Account site where this image lives.

**Comment by itsMeDavidV** [comment]
Right, I'm thinking there's a possibility for a new source for correct option codes in the API.

**Comment by Urkman** [comment]
I also think, there is a valid way to get the option codes... Somewhere...
Tesla also needs them in their app...

**Comment by Urkman** [comment]
Something like this? 
[https://gist.github.com/Kemmey/b18964d42c5617b2247fa7bacbfa2638](https://gist.github.com/Kemmey/b18964d42c5617b2247fa7bacbfa2638)

**Comment by MikeBishop** [comment]
Yes, that is one major piece of code I drew from to generate my own translation.

**Comment by Urkman** [comment]
Perhaps you can share the code?

**Comment by Urkman** [comment]
@timdorr Perhaps we should add these mappings somewhere to the Documentation. And enhance it, when there will be new mappings?
As for my MY(09/2022), the wheels are: "Induction20Black". That is currently not handled by the mapping...

**Comment by Urkman** [comment]
I think it would be grate, to have a source of information for this...
btw, here are the codes for the two new colors and the wheels used in Germany:

        // Induction20Black: WY20P
        // Gemini19: WY19B

        // Quicksilver : PN00
        // MidnightCherryRed  : PR00

**Comment by MikeBishop** [comment]
Added, thank you!  I'll take any other updates [here](https://github.com/MikeBishop/MMM-Powerwall/issues/5).

**Comment by masonticehurst** [comment]
Discovered this after opening #794 , but it appears that an imageURL can be obtained from this endpoint:
`https://www.tesla.com/teslaaccount/oxp-bff-api/user-orders`
though, I haven't been able to use the same bearer token that I use with the `https://owner-api.teslamotors.com` API.
