### ISSUE TITLE
[QUESTION] - shift_state (Parked, Driving,...)

### ISSUE THREAD

**Issue by Ahmadre** [timdorr/tesla-api#194]
At first: thank you sooo much @timdorr for this API!

I am trying to encounter the driving state of the tesla, but I am getting:

```json
   "shift_state": null,
   "speed": null,
```

I am not getting something like: "Driving", "Parked", "Reverse", etc.

Does that mean, that `null` stands for `Parked`?

thanks :) 😊

**Comment by davidhodge** [comment]
Null tends to mean the car is parked and in some level if sleep state. Technically i think of it as “no data” but for the most part you only get into that state when parked for a bit.

Otherwise you’ll see “D”, “N”, “R”, “P”, and occasionally an empty string.

**Comment by Ahmadre** [comment]
@davidhodge Thank you so much :) I was also thinking of that in `null` state is parking.
