### ISSUE TITLE
Docs site down?

### ISSUE THREAD

**Issue by adilanchian** [timdorr/tesla-api#196]
Hey just curious if you were aware or new why the site is down? I'm slightly frightened that Tesla is starting to send out requests to take these or down or blocking these requests all together.

Let me know and much appreciated 
![Screen Shot 2020-06-04 at 5 59 13 AM](https://user-images.githubusercontent.com/13204620/83754404-256d2000-a629-11ea-9fae-d0f7bdde85d8.png)

**Comment by kribensa** [comment]
It’s working fine for me – perhaps a local DNS issue?

**Comment by adilanchian** [comment]
Interesting... Just had multiple try it on different seems to be down. I appreciate the reply!

**Comment by adilanchian** [comment]
Looks like this is a working path:

https://web.archive.org/web/20200513082634/https://tesla-api.timdorr.com/

Really, I just wanted to make sure the API wasn't down :P

**Comment by kribensa** [comment]
Note that the web.archive.org page will of course be an older version

I tried it from a UK and a USA (East coast) machine, and both were okay (both showed the page, and the IP resolved to 165.22.35.90), so it looks like either your own machine’s DNS, or your ISP’s DNS is having issues

If it’s your own machine, it should be resolved by flushing the DNS (google for how to do that on your OS) or just turning it off and on again 😉
If it still fails, you could get around the DNS issue by adding this IP entry to your HOSTS file:

165.22.35.90       tesla-api.timdorr.com

(It’s worth removing it every now and again and testing it until it starts working without it)

But to answer your specific concern, it looks like the api doc page is still up and running and it’s jut a problem at your end
Hope this helps

**Comment by timdorr** [comment]
GitBook is having a big outage: https://twitter.com/GitBookStatus/status/1268528465990619137

I've set up their backup CNAME for the site. Hopefully that should propagate quickly.

**Comment by adilanchian** [comment]
@timdorr thanks for the heads up here! Just checked and things are looking awesome :). Thanks for the heads up.
