### ISSUE TITLE
Trunk/Frunk not opening - Invalid Value

### ISSUE THREAD

**Issue by Ahmadre** [timdorr/tesla-api#197]
<img width="714" alt="Bildschirmfoto 2020-06-12 um 20 31 29" src="https://user-images.githubusercontent.com/18512224/84535263-c58f0d00-aceb-11ea-8a4b-48a2968668e2.png">

None of the other issues helped me here.

**Comment by davidhodge** [comment]
how consistently is this happening for you?

**Comment by Ahmadre** [comment]
@davidhodge Everytime! It happens on full charge, less charge. I tried also front. It's not possible to open the trunk/frunk

**Comment by Ahmadre** [comment]
I also tried: `which_trunk=ft` or `which_trunk=rt`

**Comment by davidhodge** [comment]
ok. So I've not used this particular command, but I've had some commands (lock/unlock) fail some of the time for Nikola users in unpredictable ways. If you have access to another vehicle, it might be worth checking there.

Also, what happens with no param?

**Comment by davidhodge** [comment]
according to this, you may need to pass it in the body as opposed to as a parameter. https://teslamotorsclub.com/tmc/threads/model-s-rest-api.13410/page-125

**Comment by timdorr** [comment]
Yes, these are POSTs, so the input belongs in the body. It won't work as a query parameter.

**Comment by Ahmadre** [comment]
Thank you soooo much @davidhodge and @timdorr :))) Sorry didn't see that while googling
