### ISSUE TITLE
set_temps is always setting both

### ISSUE THREAD

**Issue by Ahmadre** [timdorr/tesla-api#200]
<img width="660" alt="Bildschirmfoto 2020-06-15 um 06 18 08" src="https://user-images.githubusercontent.com/18512224/84617698-1b240f00-aed0-11ea-93e2-379d712498dd.png">

The `set_temps` interface is working, but when I set it, both driver and passenger temps are equal.

Headers:
`Content-Type: application/json`

My result:

```
    "driver_temp_setting": 17.0,
    "passenger_temp_setting": 17.0,
```

Am I doing something wrong here?

**Comment by timdorr** [comment]
This has been an unwritten thing for a bit now. The app only displays one temperature setting, despite the API accepting two inputs. I'll add a note about it.
