### ISSUE TITLE
How to Share a Location to Tesla ? Thanks

### ISSUE THREAD

**Issue by ffllc** [timdorr/tesla-api#201]
API:
https://owner-api.teslamotors.com/api/1/vehicles/{remote_id}/command/share

Post JSON:

{
              "type": "share_ext_content_raw",
              "value": {
                "android.intent.extra.TEXT": "Here"
              },
             "locale": "zh-CN",
              "timestamp_ms": "1539465730"
            }
Could you please show me a example for Here ?
I had try any things but all got a mistake : {"response":null,"error":"upstream internal error","error_description":""}

"22.63,114.131" ,
"Latitude=22.63,Longitude=114.1311907846",
"123 Main St, City, ST 12345\n\nhttps://goo.gl/maps/X"
 "这里是福兴五金店(金鸡路店)：福建省龙岩市新罗区曹溪路与金鸡路交叉口西150米 查看详情>>http://j.map.baidu.com/39/t78  #百度地图#",

**Comment by timdorr** [comment]
I'm not sure about the formatting in a different locale. But I would also try updating the `timestamp_ms` to the current timestamp.
