### ISSUE TITLE
[QUESTION] - different car_type

### ISSUE THREAD

**Issue by Ahmadre** [timdorr/tesla-api#202]
Hi @timdorr hope you're good and safe :),

we encountered with a customer, that our app is crashing with a model s tesla. I think it's because we only catch the car_types:
- `model3`
- `modely`
- `modelx`
- `models`

is there also the car_type `models2` ?

**Comment by timdorr** [comment]
Yes, I believe that's for the front fascia redesign. My P90D is a `models2` and my prior 85 was a `models`.

**Comment by Ahmadre** [comment]
great! it works :) thanks @timdorr
