### ISSUE TITLE
Add support for the Scheduled Departure

### ISSUE THREAD

**Issue by fniewijk** [timdorr/tesla-api#205]
I'd like to control the Scheduled Departure setting and I'd love to have this functionality added.

The Scheduled Departure feature is currently preventing my smart charging app from working perfectly, because I'm manually sending ON and OFF commands to the charger and this feature seems to interfere with it.

I don't have a Tesla right now to find the endpoints and document it unfortunately. But if someone can supply this, I would be more than happy to open a PR with the functionality.

**Comment by timdorr** [comment]
This isn't available on the API surface as of yet. There's nothing we can do until Tesla adds it. 

You could simulate the feature by stopping and starting the charger. That's the best you can do for now.

**Comment by fniewijk** [comment]
Too bad. Thanks for the quick response!
