### ISSUE TITLE
List of charging states

### ISSUE THREAD

**Issue by Ahmadre** [timdorr/tesla-api#207]
I got 4 charging states detected:

- Disconnected
- NoPower
- Charging
- Complete

but sometimes in a weird state our app comes to an error parsing a charging state.

Are these all, or did I miss one?

**Comment by fus3d** [comment]
Stopped

**Comment by Ahmadre** [comment]
@fus3d Thanks, that's really helpfull :)

**Comment by jonasman** [comment]
Is there a state for waiting to start, when we schedule the charge? I think i saw it once and maybe it is one o those in the list

**Comment by Ahmadre** [comment]
> Is there a state for waiting to start, when we schedule the charge? I think i saw it once and maybe it is one o those in the list

Jup: it's called: "NoPower". You can handle it like: "Ready to Charge"
