### ISSUE TITLE
Network (WfFi) Status

### ISSUE THREAD

**Issue by rnhurt** [timdorr/tesla-api#208]
Is there an API for the network (WiFi) connection for the car?  I looked around a bit but couldn't find anything relevant.

**Comment by GaPhi** [comment]
As far as I know, state is 'asleep' in case of wifi, 'offline' otherwise.
But 'online' is used in both cases when car is awake.

**Comment by rnhurt** [comment]
Hmmm.... I was wanting to be able to view, and maybe control, the WiFi connection.  Name, signal strength, MAC address, etc.  But it looks like those things might not be available to the API.

**Comment by timdorr** [comment]
Nope, those aren't on the API.
