### ISSUE TITLE
Vehicle State Screen Value 5

### ISSUE THREAD

**Issue by RCdiy** [timdorr/tesla-api#211]
Model Y 
center_display_state
5 is Charging Screen. Not 3?
https://tesla-api.timdorr.com/vehicle/state/vehiclestate 
![IMG_0474](https://user-images.githubusercontent.com/20209851/91897665-9d6ad680-ec68-11ea-9c5e-c2deede0c3ab.jpeg)

**Comment by timdorr** [comment]
Might be a "scheduled charge" screen? If you've discovered some more, a PR would be appreciated. There are obviously gaps in the numbers.
