### ISSUE TITLE
Q&A Forum?

### ISSUE THREAD

**Issue by RCdiy** [timdorr/tesla-api#214]
Is there a Q&A forum where developers help each other?
This is an awesome resource. I don't think however you want to spend time helping me get up to speed on a couple of things. If you don't mind then may we use this issue as a Q&A thread that always stays open?
I have gone through closed issues to see what I can pick up.

**Comment by timdorr** [comment]
Most folks use TMC. Whenever GitHub opens up Discussions to more repos, I'll turn it on here for sure.
