### ISSUE TITLE
How to enable controls when generating a token

### ISSUE THREAD

**Issue by snckirkmarken** [timdorr/tesla-api#222]
Hello. I hope I didn't miss it in the docs and perhaps not technically an "issue", but I can't see where one would generate a token which enables controls.

I assume this is possible because Teslafi mention it as something doable when a user might enter their Tesla credentials through their own form, but I would rather generate the token myself.

Please let me know how I might do this?

Thanks,
Simon

**Comment by timdorr** [comment]
https://tesla-api.timdorr.com/api-basics/authentication

**Comment by snckirkmarken** [comment]
Thanks for the response @timdorr, but I'd already read the page, and had already generated myself a token that's working fine with Teslafi, except for one thing: it's not enabled for controls.

The page docs don't mention control anywhere, unless I'm missing it.

**Comment by timdorr** [comment]
That would be a TeslaFi question, not one for these docs.

**Comment by snckirkmarken** [comment]
Fair comment. I mistakenly assumed they'd used your API docs as a basis. I'll contact them. If I find it out, I'll do a PR for the change for the docs, I you wanted to incorporate it.

**Comment by llamafilm** [comment]
I asked Teslafi about this and they said there is only one kind of API token, it doesn’t have different scopes. You just have to check the box on the website to enable control.
