### ISSUE TITLE
vehicles/{id} not working?

### ISSUE THREAD

**Issue by tekgiant** [timdorr/tesla-api#223]
I feel like I'm losing my mind here and likely missing something really stupid...

My steps:
1. ✔️ Sign in
2. ✔️ Get Vehicle List: api/1/vehicles
``` json
[
    {
        "id": 381...,
        "vehicle_id": 889...,
        "vin": "5YJ...",
        "display_name": "MBX",
        "option_codes": "AD15,MDL3,PBSB,RENA,BT37,ID3W,RF3G,S3PB,DRLH,DV2W,W39B,APF0,COUS,BC3B,CH07,PC30,FC3P,FG31,GLFR,HL31,HM31,IL31,LTPB,MR31,FM3B,RS3H,SA3P,STCP,SC04,SU3C,T3CA,TW00,TM00,UT3P,WR00,AU3P,APH3,AF00,ZCST,MI00,CDM0",
        "color": null,
        "access_type": "OWNER",
        "tokens": [
            "b90...",
            "d70..."
        ],
        "state": "online",
        "in_service": false,
        "id_s": "381...",
        "calendar_enabled": true,
        "api_version": 10,
        "backseat_token": null,
        "backseat_token_updated_at": null,
        "vehicle_config": null
    }
]
```
3. ❌ Get Vehicle by Id: api/1/vehicles/381...  (ensured I was using the id property from the vehicles list, not the vehicle_id property)
      This request returns a 404
``` json
{
    "response": null,
    "error": "not_found",
    "error_description": ""
}
```

Just to double check, even though I assumed it wouldn't work, I did try using the vehicle_id as well, but got the same response. What am I missing here?

Also, just to avoid any weird code issues, I've been trying this in Postman and getting the same results, so I'm confident it's not a code issue.

GET /api/1/vehicles/381... HTTP/1.1
Host: owner-api.teslamotors.com
Authorization: Bearer ...
Cache-Control: no-cache
Postman-Token: f3afcfa7-4256-4ac7-947f-196714e5a321

**Comment by timdorr** [comment]
It's working on my end. You're using the right ID number (`id` or `id_s`), so I don't see anything obviously wrong here. I'd keep double- and triple-checking things with your code.
