### ISSUE TITLE
Vehicle ID supplied to the /vehicles/{id} endpoint has changed to id_s

### ISSUE THREAD

**Issue by milesburton** [timdorr/tesla-api#224]
Tesla have changed what is supplied to the /vehicles/{id} to {id_s}. You can get this id from the same /vehicles endpoint.

**Comment by timdorr** [comment]
These fields literally have the exact same number. They provide the `id_s` version, as the numeric form in `id` is beyond the 32-bit limit and many languages and JSON libraries either won't parse it or parse it incorrectly. I would check that your libraries have support for large numbers. But the data coming over the wire has the exact same values for `id` vs `id_s`, just numeric vs string form.

**Comment by milesburton** [comment]
Hey Tim,

When I checked the Tesla API earlier it was different - I tested it by hand
in Advanced Reset Client.

**Comment by milesburton** [comment]
Here's an example straight off the Tesla site. (I've removed the previous characters for anonymity 

`"id": 76
,
"id_s": "79",`

**Comment by ltfiend** [comment]
Both exist and both are contain the same data as Tim said.  I just verified on mine in the raw data

for reference:

{'id': xxxxxxxxxxxxxxx87, 'user_id': xxxxx1, 'vehicle_id': xxxxxxxx6, 'vin': '5Yxxxxxxxxxxxxx', 'display_name': 'Tess', 'option_codes': 'AD15,MDL3,PBSB,RENA,BT37,ID3W,RF3G,S3PB,DRLH,DV2W,W39B,APF0,COUS,BC3B,CH07,PC30,FC3P,FG31,GLFR,HL31,HM31,IL31,LTPB,MR31,FM3B,RS3H,SA3P,STCP,SC04,SU3C,T3CA,TW00,TM00,UT3P,WR00,AU3P,APH3,AF00,ZCST,MI00,CDM0', 'color': None, 'access_type': 'OWNER', 'tokens': ['xxxxxxxxxxxxxx', 'xxxxxxxxxxxxxxx'], 'state': 'online', 'in_service': False, 'id_s': 'xxxxxxxxxxxxxxx87', <snip>

**Comment by milesburton** [comment]
OK Confirmed, it looks like the number is trunced in JS so it doesn't decode correctly. This is down to the javascript number datetype we think. Likely why Tesla included the string variant. 

Thanks Both
