### ISSUE TITLE
set_charge_limit as distance

### ISSUE THREAD

**Issue by rkaderli** [timdorr/tesla-api#229]
Hello Tim
I'm using in my logic set_charge_limit to the the % value it should charge max.

However it would be easier and possibly more accurate to adjust that in km/mile. Is there such option in the API? I hear in the App people can adjust a distance limit since some time.

Thanks!
Reto

**Comment by timdorr** [comment]
The app is just doing the math based on the current percentage and predicted range. It still sends the request to the API as a percentage.
