### ISSUE TITLE
set_charge_limit not working? 

### ISSUE THREAD

**Issue by mooxitani** [timdorr/tesla-api#249]
I am probably missing something stupid here, but calling set_charge_limit always changes the percentage to 50, completely ignoring the percentage that I have set in the parameters. 

URL: https://owner-api.teslamotors.com/api/1/vehicles/id:/command/set_charge_limit?percent=90

**Comment by timdorr** [comment]
You have to put the parameters for any request in the POST body of the request, not in the query string of the URL.
