### ISSUE TITLE
Model 3 /command/set_temps not working properly

### ISSUE THREAD

**Issue by sven-v-t-veer** [timdorr/tesla-api#254]
When I send  https://owner-api.teslamotors.com/api/1/vehicles/123123123/command/set_temps?passenger_temp=20&driver_temp=20 to the API, the temperature is ignored by my model 3 (2021). I can start and stop climate control (climate + battery heating icon appear in app) but when the set_temps endpoint is called the temperature in the car is set to "LO".

I do get a 200 HttpResponse and of course tesla returns "true".

Any idea if this has changed for the (new) model 3?

**Comment by sven-v-t-veer** [comment]
Same seems to hold true for https://owner-api.teslamotors.com/api/1/vehicles/123123123/command/set_preconditioning_max?on=true This seems to do nothing

**Comment by timdorr** [comment]
You need to put the parameters in the POST body, not the URL. They will ignore them otherwise.
