### ISSUE TITLE
Document all possible values of "center_display_state"

### ISSUE THREAD

**Issue by itsMeDavidV** [timdorr/tesla-api#255]
Just want to start out by saying thanks for this wonderful resource. 

I was hoping that there could be some fill in the gaps for possible values of "center_display_state".

Currently on docs the known values read as: 

0 | Off
2 | Normal On
3 | Charging Screen
7 | Sentry Mode
8 | Dog Mode

However I have seen instances where 4 & 5 were returned as values. Also I have a huge hunch camp mode can be reported as a value, as it only makes sense. (if any one has any info on how to determine if camp mode is active another way (eg: maybe "climate_keeper_mode") that would be heavily appreciated, as that mission is what brought me on this rabbit hole).

Before you ask, I currently I don't have access to a Tesla to test with for the foreseeable future, otherwise I would do this myself.

Thanks!

**Comment by ChadMoran** [comment]
0 - Off
2 - On, standby (also camp mode)
3 - On, can drive
4 - On, can drive
5 - Charging external - Charing stats big for external viewing
6 - Unlocked external - This is the "place the key card here to unlock" screen
7 - Sentry
8 - Dog mode
9 - Media

**Comment by itsMeDavidV** [comment]
@ChadMoran Sweet! Thanks for this. So it would seem from your findings that "center_display_state" is not a reliable way of determining if Camp Mode is on since the vehicle could just be in standby, but not Camp mode. Do you happen to know by chance if "climate_keeper_mode" has an explicit value for Camp Mode?

**Comment by ChadMoran** [comment]
```
on
off
camp
dog
```

Those are the values I've observed for `climate_keeper_mode`.

**Comment by itsMeDavidV** [comment]
@ChadMoran This helps a ton. Thank you
