### ISSUE TITLE
authentication problem ? - endpoint_deprecated:_please_update_your_app

### ISSUE THREAD

**Issue by B-Hartley** [timdorr/tesla-api#259]
Hi,

I use Home Assistant with the tesla_gateway scripts to control my powerwall.
I seem to have lost connection.
In my logs, I get....
{"response":"endpoint_deprecated:_please_update_your_app."}

Which google suggests is due to a change with the authentication methods used.
Is this issue within this API? or is the problem more likely to be in my script?

Thanks in advance,
Bruce.

**Comment by IMgoRt** [comment]
> Hi,
> 
> I use Home Assistant with the tesla_gateway scripts to control my powerwall.
> I seem to have lost connection.
> In my logs, I get....
> {"response":"endpoint_deprecated:_please_update_your_app."}
> 
> Which google suggests is due to a change with the authentication methods used.
> Is this issue within this API? or is the problem more likely to be in my script?
> 
> Thanks in advance,
> Bruce.

The problem is Tesla implementing a new auth method in prep for 2FA, people are working out how to get round it

**Comment by timdorr** [comment]
See #215
