### ISSUE TITLE
Clarify v3 auth API is fully OAuth2 compliant

### ISSUE THREAD

**Issue by uhthomas** [timdorr/tesla-api#273]
Hi, this is very closely related to #260 but I didn't want this to get lost in there as I think it's quite important.

The Tesla v3 auth API is fully OAuth2 compliant, and such a few steps which are outlined in the documentation can be simplified. The problem we face currently is there is no way to issue new client IDs/secrets and so, we are forced to use the parameters Tesla has put in place. Such, the redirect URL is only allowed to be `https://auth.tesla.com/void/callback`.

The authentication process therefore requires two steps:
* Standard OAuth 2 flow.
* Emulate what a user would do in browser, to work around the inability to change the redirect URL.

Please see [uhthomas/tesla/cmd/login/main.go](https://github.com/uhthomas/tesla/blob/3e1bb8a19d3cd53aa2a56b97b6efd2554b5fa809/cmd/login/main.go#L43-L67) for an example of using native OAuth2 packages, in conjunction with the emulation.

It should also be important to note that the `code_challenge` and `code_verifier` are part of the [OAuth2 spec (PKCE)](https://www.oauth.com/oauth2-servers/pkce/).

**Comment by uhthomas** [comment]
It's also worth noting, the final step of exchanging the v3 OAuth2 token, for a legacy owner API token is entirely optional (and should not be recommended). The access tokens obtained through the v3 auth API work exactly the same as those legacy tokens. It would be good to include it as a footnote though, as it might be useful to someone 😄

**Comment by timdorr** [comment]
It is largely in line with OAuth, which makes sense because they probably implemented it using an existing library, rather than building from scratch. There appears to be some variation from the spec around the PKCE parts (it only accepts an 86 character string for the verifier). 

I've already got a note at the top about the SSO service using OAuth 2.0. I don't want to take anything away from the docs, as it requires some nuance from a typical flow (such as Twitter or Google) and pieces together parts of the spec (Authorization Code, PKCE, Bearer Tokens, etc.). I think what is there is sufficient.

**Comment by timdorr** [comment]
> It's also worth noting, the final step of exchanging the v3 OAuth2 token, for a legacy owner API token is entirely optional (and should not be recommended). The access tokens obtained through the v3 auth API work exactly the same as those legacy tokens. It would be good to include it as a footnote though, as it might be useful to someone 😄

Hmm, I didn't actually think to check this. In that case, I can at least remove the last step. That might even go away in the future, too.

**Comment by uhthomas** [comment]
> it only accepts an 86 character string for the verifier

I've just verified this is not the case. I do not see any deviation from the OAuth2 spec at all. I agree that the "nuances" shouldn't be removed, but documenting explicit OAuth2 flows may make the docs less legible than if it were to focus on emulating the actual login / MFA flow.

**Comment by timdorr** [comment]
Actually, while you can use the access token from the SSO server, it expires in 5 minutes, so it's pretty useless. You should exchange for an Owner's API token so you can continue to use it for 45 days.

**Comment by timdorr** [comment]
> I agree that the "nuances" shouldn't be removed, but documenting explicit OAuth2 flows may make the docs less legible than if it were to focus on emulating the actual login / MFA flow.

I'm not sure I understand what you're asking for here. I'm not going to switch the docs to just say "use OAuth 2.0, lol" and call it a day. Many folks have no idea what OAuth is or how it works, so walking them through the specifics of what to input into the various endpoints is important. 

If you have a specific suggestion, I would recommend a PR instead. Discussing docs out of context from them is always a problem, I've found.

**Comment by uhthomas** [comment]
Access tokens aren't supposed to live a long time. The refresh token will live a lot longer, and should be automatically managed by the HTTP transport of whichever OAuth2 package/library being used.

**Comment by uhthomas** [comment]
To clarify - my intent was to shed light on the fact that it's fully compliant with the OAuth2 specification. Users _should not_ be re-implementing OAuth2 on their own as the specific is nuanced and has lots of variation. The docs should recommend people to use their native language OAuth2 libs, and direct them to external documentation that clearly describes OAuth2 if they're interested, rather than Tesla-specific.

Anyway, hope this was helpful.
