### ISSUE TITLE
New API attribute: command_signing

### ISSUE THREAD

**Issue by stx** [timdorr/tesla-api#324]
It appears that the API has begun reporting {"command_signing": "off"} for all vehicles.

I suspect this is for an upcoming change that will prevent all commands that aren't coming directly from the official app in real-time, which is going to break all 3rd party apps and automations.

**Comment by sammarcus** [comment]
Yikes. Not promising. This would be really, really unfortunate (albeit not surprising).

**Comment by timdorr** [comment]
Assuming there's some sort of signature component to API requests, that must be generated in the app somehow. It will be reversible. 

There is currently no mention of this anywhere in the latest version of the app (3.10.9-433), so they would require a long period of time for folks to update their apps. It took the SSO system a full 4 months to start being enforced, with support for it showing up in the app many months before that. So, I wouldn't expect anything like this to be enforced until later in the year, at the earliest.

Also, I'm not 100% sure why this would be needed anyways. OAuth 2.0 abandoned the signature requirements of 1.0a, given they were a faulty sense of security in the request. We already have to get past authentication to get to the API anyways, which is fully encrypted. There's no MITM or similar attack vector here, so I don't know what the issue might be that they are attempting to solve.

Anyways, until this actually proves to be something of substance, this is all just speculation. I'm going to close this out until the situation changes.
