### ISSUE TITLE
https://auth-global.tesla.com/oauth2/v3/authorize seems to give a 301

### ISSUE THREAD

**Issue by jordyperlee** [timdorr/tesla-api#337]
I noticed my app was timing out on calls, it seems that when calling the https://auth-global.tesla.com/oauth2/v3/authorize URL it returns a 301 Moved Permanently

**Comment by pgalbavy** [comment]
That should be auth.tesla.com in the brave new world

**Comment by jordyperlee** [comment]
Was indeed the case, thanks!
