### ISSUE TITLE
"Previously Repaired" and "Clean History" option code

### ISSUE THREAD

**Issue by Kikobeats** [timdorr/tesla-api#354]
I noted Tesla website is now reporting this information for used inventory cars

<img width="945" alt="Screen Shot 2021-04-01 at 13 43 35" src="https://user-images.githubusercontent.com/2096101/113289253-43122100-92f0-11eb-8831-a220053d9d85.png">

- Previously repaired VIN: `5YJ3E1EA2JF007539`
- Clean History VIN: `5YJ3E1EA9JF173444`

Good great to know if this is linked with an option code.

**Comment by timdorr** [comment]
It's likely not. Option codes are applied when the car is built, not after the fact. I did an upgrade to MCU2 and HW3, but that didn't change any of my option codes. Plus, options are a feature of the car itself, not its history. I doubt this is going to be made available on the API ever.
