### ISSUE TITLE
New Auth. Step 2: Page not found

### ISSUE THREAD

**Issue by infxmousrogue** [timdorr/tesla-api#383]
Hi all, when trying the new OAuth method for the TeslaAPI as documented [here](https://tesla-api.timdorr.com/api-basics/authentication#get-https-auth-tesla-com-oauth-2-v-3-authorize).

I'm running into a problem where when POSTing step 2 it returns a "Page not found" Why does this occur? I am using the same cookie as with the step 1 GET request. Copied all the other hidden fields from the get request and it's still not working. Did anyone run into the same issue?

Picture of my params:
![image](https://user-images.githubusercontent.com/54747969/119487786-17dd0880-bd5a-11eb-9f9e-683e9680b316.png)

Picture of my body params:
![image](https://user-images.githubusercontent.com/54747969/119487845-275c5180-bd5a-11eb-9e9c-c0eb58819ffa.png)

body parameters of credential and identity are not in the picture for obvious reasons but they're also there.

I am currently testing this through Postman to check if I understand everything correctly and if it works. When I verify everything I will be writing the script in Swift.

EDIT: Every request after setting up the same cookies as the get request results in a page not found. When deleting the cookies it then shows the Tesla - SSO Login page again.

**Comment by the-mace** [comment]
Same problem in https://github.com/timdorr/tesla-api/discussions/508, https://github.com/timdorr/tesla-api/discussions/352,  https://github.com/timdorr/tesla-api/discussions/614
