### ISSUE TITLE
Updated API methods

### ISSUE THREAD

**Issue by timdorr** [timdorr/tesla-api#4]
I need some help documenting the latest API methods found, including any hidden ones. For instance, `set_charge_limit` was added due to variable charge limiting introduced in the 4.5 firmware. There are possibly others. 

I'll leave this issue open so others can comment and indicate any endpoints they've found.

**Comment by raptortech-js** [comment]
It looks like the docs are still missing stream, at least on Apiary.

**Comment by timdorr** [comment]
@wumpus and @raptortech-js If you guys want to submit a PR, I'd be super-happy to accept. I haven't had much time to get to updates, as I've been more focused on my @rackt efforts lately.
