### ISSUE TITLE
Sunroof control (not working on Tesla's end)

### ISSUE THREAD

**Issue by dburk1013** [timdorr/tesla-api#43]
After lots of playing around, I've been able to use almost all of the documented API calls EXCEPT the sun_roof_control. 

Whether I'm using the interface provided by Tim Dorr or a simple (ish) Java application I've written, I can't seem to find any combination of sunroof calls parameters that work. States of "close", "open", "comfort", "move" all return 400 errors (`{"response": null,  "error": "invalid_state", "error_description": ""}` but "vent" returns a 200 but with the following: `{"response": {"reason": "unknown state requested: ", "result": false}}`. Results seem to be the same with and without "percent" provided. 

I'm definitely working on a car that has a panosunroof. I'm not sure it should make any difference, but the car is about 2 weeks out from delivery so it has the newest hardware. When I do a  data_request/vehicle_state on the vehicle, I get the following back (among other parts): `"sun_roof_installed": 2,"sun_roof_percent_open": 0,"sun_roof_state": "unknown",`

Does anyone know of any differences in the API for the sunroof? Are there other combinations of parameters that anyone has had any success with.

Thanks so much for any help you can give!

**Comment by jonasman** [comment]
The app only allows you to vent anyway. So maybe the other options were removed.
Later i can check on my car what is returned by that api. I have AP1 with pano

**Comment by jonasman** [comment]
`"sun_roof_installed" = 2;
        "sun_roof_percent_open" = 0;
        "sun_roof_state" = unknown;`

**Comment by dburk1013** [comment]
Thanks for the feedback. For what I'm trying to do, all I want it to do is close. I'm building a phone app that will recognize when you're in the car and a call comes in and then closes the sunroof. Seems simple enough.

**Comment by irritanterik** [comment]
@dburk1013 : haven't tested this call last 2 months, but maybe my implementation of the code helps:
https://github.com/irritanterik/homey-tesla.com/blob/master/lib/tesla.js
(lib with promisses, used for home automation app)

**Comment by mseminatore** [comment]
Another impl is available here:
https://github.com/mseminatore/TeslaJS/blob/master/TeslaJS.js

**Comment by dburk1013** [comment]
irritanterik and mseminatore: I've looked at your implementations and I'm pretty sure they match mine (other than JS v Java).
"close" and "vent" produce 200 results: {"response":{"reason":"unknown state requested: ","result":false}}
"open" and "comfort" produce 400 results: {"response":null,"error":"invalid_state","error_description":""}

I wonder if either of you might run a test using your code to see what results you might be getting for the four states.

One curious note is that the Android app from Tesla has only a "Vent" roof button alternating with a "Close" roof button. I wonder if the other states don't work. But more oddly, the roof button on the Android app actually moves the roof, while mine doesn't.

Again, all help much appreciated.

**Comment by mseminatore** [comment]
OK I tested and I am getting 400 returns for all states that I tested.

**Comment by dburk1013** [comment]
Thanks. I guess I'm some ways that's a relief since there's only so much head banging I can take. I wonder if that API has gotten "dumber" or if the syntax has changed. Does anyone have any idea where you'd go to find out?

**Comment by mseminatore** [comment]
It seems this is a known issue
<https://teslamotorsclub.com/tmc/threads/model-s-rest-api.13410/page-89>,
perhaps related to upcoming changes to the API.

**Comment by dburk1013** [comment]
And before I leave the thread, I wanted to leave one additional piece of information in the "for what it's worth" category: the results are mildly different between using the proxy server and using the actual production server. But in each case, even with "200" results, the pano roof doesn't move.

**Comment by mseminatore** [comment]
Could it be that they’ve changed the comm to vehicles so that this will only work with the next update?

Sent from my Windows 10 phone

**Comment by timdorr** [comment]
They've changed some of the parameters for sun roofs. Not sure why (maybe all-glass-roof-related?), but it just needs the right params to work.

**Comment by dburk1013** [comment]
And is there updated documentation on what the right parameters are? Ultimately all I really need is to have a "close" command that actually closes the roof.

**Comment by tekkkon** [comment]
They used to support "open", "close", "vent", "comfort" and "move" to xxx percent. But recent test shows only "vent" and "close" commands work.

**Comment by timdorr** [comment]
> They used to support "open", "close", "vent", "comfort" and "move" to xxx percent. But recent test shows only "vent" and "close" commands work.

I can confirm this as well. The Android app still references the stop, open, and move states, but they don't appear to be working server-side. I'll keep this open, but for now it's blocked on the server side.

**Comment by dburk1013** [comment]
I'm not sure if this is the right place to leave this question and if it's not, I hope someone will direct me to the right place. Thanks to a number of contributors who are much wiser than I, I've got a plain vanilla version of what I'm trying to do in Java working in EclipseJavaNeon. But ultimately, I'm trying to get this into an Android app and once again, there is something about how I'm using the API that's just not right (or I'm just too uneducated to be programming this stuff). There are two parts to my problem right now and a kind of third problem listed way below.
----------------------------------------------------------------------------------------------------------------
**1) On the effort to get the access token**, I can get the token but only if all the parameters are in the URL itself with https://private-anon-3f2af7cab3-timdorr.apiary-proxy.com/oauth/token?client_id=e4a9949fcfa04068f59abb5a658f2bac0a3428e4652315490b659d5ab3f35a9e&client_secret=c75f14bbadc8bee3a7594412c31416f8300256d7668ea7e6e7f06727bfb9d220&email=myemail@hotmail.com&password=[my password]&grant_type=password  

This works but it seems as if I should be able to pass the parts either as JSON or the equivalent of headers so that it's not passed in plain text with the password. Here's the code that I'm using. This is in a separate thread as required by Android and I THINK I'm managing the Async stuff correctly. So the following works but I'd like to get the parameters out of the URL if there's a way to do it:

String realUrl = "https://owner-api.teslamotors.com/oauth/token?grant_type=password&client_id={id token}&client_secret={client secret token}&email={myemail@mydomain.com}&password={mypassword}";
URL url = null;
try {
         url = new URL(realUrl);
} catch (MalformedURLException e) {
         e.printStackTrace();
}
HttpsURLConnection myURLConnection = null;
try {
         myURLConnection = (HttpsURLConnection) url.openConnection();
} catch (IOException e) {
  e.printStackTrace();
}
try {
         myURLConnection.setRequestMethod("POST");
} catch (ProtocolException e) {
         e.printStackTrace();
}
myURLConnection.setConnectTimeout(3000);  **//THIS LINE DOESN’T SEEM TO MAKE ANY DIFFERENCE WHEN I LOOK AT DEBUG**
myURLConnection.setReadTimeout(3000);      **//DITTO WITH THIS LINE**
myURLConnection.setRequestProperty("User-Agent", "Mozilla/5.0");
myURLConnection.setRequestProperty("Content-Type", "application/json");
myURLConnection.setDoOutput(true);
myURLConnection.setDoInput(true);

_/*Tried to put all of the parameters into JSON and write it here, but this didn’t work
String json = "{\"grant_type\":"\password,client_id\":\"[id token]\","\client_secret\":"\[client secret token]\",\"email\":\"myemail@mydomain.com\",\"password\":\"mypassword\"}";
DataOutputStream dStream = null;
try {
         dStream = new DataOutputStream(myURLConnection.getOutputStream());
         dStream.writeBytes(json);
         dStream.flush();
         dStream.close();
} catch (IOException e) {
         e.printStackTrace();
} */_

int response = 0;
try {
         response = myURLConnection.getResponseCode();
} catch (IOException e) {
         e.printStackTrace();
}
StringBuffer result = new StringBuffer();
BufferedReader rd;
try {
         rd = new BufferedReader(new InputStreamReader(myURLConnection.getInputStream()));
         String line = "";
         while ((line = rd.readLine()) != null) {
                 result.append(line);
         }
         rd.close();
} catch (IOException e) {
         e.printStackTrace();
}
myURLConnection.disconnect();
accessToken = [subroutine pulls global String accessToken from result; works];
return;
----------------------------------------------------------------------------------------------------------------
**2) Once I have a good access token, I'm next trying to get the vehicleID.** The following code is returning a 404 from the server. I suspect I'm missing something really easy and obvious. Any help here again would be greatly appreciated:

String realUrl = "https://owner-api.teslamotors.com/api/1/vehicles";
URL url = null;
try {
         url = new URL(realUrl);
} catch (MalformedURLException e) {
         e.printStackTrace();
}
HttpsURLConnection myURLConnection = null;
try {
         myURLConnection = (HttpsURLConnection) url.openConnection();
} catch (IOException e) {
  e.printStackTrace();
}
try {
         myURLConnection.setRequestMethod("GET");
} catch (ProtocolException e) {
         e.printStackTrace();
}
myURLConnection.setConnectTimeout(3000);  **//THIS LINE DOESN’T SEEM TO MAKE ANY DIFFERENCE WHEN I LOOK AT DEBUG**
myURLConnection.setReadTimeout(3000);      **//DITTO WITH THIS LINE**
myURLConnection.setRequestProperty("User-Agent", "Mozilla/5.0");
myURLConnection.setDoOutput(true);
myURLConnection.setDoInput(true);
myURLConnection.setRequestProperty("Authorization", "Bearer " + accessToken); //accessToken is global variable set in getAuth()

int response = 0;
try {
         response = myURLConnection.getResponseCode();
         **//response = 404!!!!**
} catch (IOException e) {
         e.printStackTrace();
}
StringBuffer result = new StringBuffer();
BufferedReader rd;
try {
         rd = new BufferedReader(new InputStreamReader(myURLConnection.getInputStream()));
         String line = "";
         while ((line = rd.readLine()) != null) {
                 result.append(line);
         }
         rd.close();
} catch (IOException e) {
         e.printStackTrace();
}
myURLConnection.disconnect();
vehicleID = [subroutine pulls global String vehicleID from result; probably works but haven’t gotten useful result yet];
return;

--------------------------------------------------------------------------------------------------
**3. If anyone has any thoughts about why the .setConnectTimeout and .setReadTimeout methods** don't seem to be changing the values for the properties when I'm looking the debugger either for myURLConnection or for the delegate property of myURLConnection, again, I would appreciate your ideas. As a related item, I learned that the .setRequestMethod, .setDoOutput, and .setDoInput methods don't change these properties for myURLConnection but do set these properties for the delegate, but this doesn't happen for the . ...Timeout methods. Why?

THANK YOU!

**Comment by timdorr** [comment]
@dburk1013 This isn't the right venue for that. If you have an issue, post a new one. Randomly commenting on this project's issues isn't going to get you help....

**Comment by pacman1176** [comment]
Set the Content-Type header to application/x-www-form-urlencoded.

`
request.setHeader("Content-Type", "application/x-www-form-urlencoded");
`

**Comment by pacman1176** [comment]
Set the content type to application/x-www-form-urlencoded.
```java 
request.setHeader(HTTP.CONTENT_TYPE, "application/x-www-form-urlencoded");
```

**Comment by Zwirc** [comment]
Any status on how to use sunroof API?
Cant get any states working

**Comment by timdorr** [comment]
@Zwirc It's on Tesla's end. They haven't fixed it.

**Comment by jonasman** [comment]
@catokolas I can use vent without the password. Are you sure you need it?

**Comment by catokolas** [comment]
@jonasman hm, you a right. must been an intermittent requirement or something else

**Comment by timdorr** [comment]
I updated the notes in the new docs, so I'm going to close this out: https://tesla-api.timdorr.com/vehicle/commands/sunroof
