### ISSUE TITLE
MASQUERADE and Safety Score

### ISSUE THREAD

**Issue by jbienz** [timdorr/tesla-api#470]
I am a subscriber of [teslafi.com](https://teslafi.com), and I wanted to use it to start tracking my safety score. Despite meeting all of the requirements, my score would not show up. So I contacted support.

TeslaFi support informed me:

> [access_type] => MASQUERADE
> 
> This means the token is not from the owners account so no Safety Score is provided.  It can also mean that the vehicle is leased but either way TeslaFi is unable to see a safety score from the account unfortunately with this set to anything besides OWNER.

I have generated a new Access Token using [TeslaAuth](https://github.com/tomhollander/TeslaAuth), and I can confirm that when I call [/api/1/vehicles](https://tesla-api.timdorr.com/api-basics/vehicles#get-api-1-vehicles) the response does indeed show `"access_type":"MASQUERADE"` after the vehicle. However:

- This is the same login I've always used
- I am the only owner of the vehicle (it was bought new)
- The vehicle is fully paid for (not leased)

My two questions:

1. Is there another explanation for `[access_type] => MASQUERADE`? It seems this might actually be an OAuth thing or a MFA thing.
2. Is there any way to get the safety score, even when `[access_type] => MASQUERADE`?

I'll pass on whatever information you can provide to TeslaFi Support.

Thank you!!!

**Comment by jbienz** [comment]
Just a follow-up. TeslaFi got back to me and said they'd made a mistake. They were able to pull my Safety Score even though my access_type was `MASQUERADE` rather than `OWNER`. But I'd still very much like to understand why mine is showing up this way.  I was only really able to find two other instances of `MASQUERADE` showing up:

1. https://forums.homeseer.com/forum/hs4-products/hs4-plugins/robotics-plug-ins-aa/teslaseer-salvesen/1486699-wont-update-with-2-teslas-on-account?p=1492482#post1492482

2. https://github.com/evcc-io/evcc/issues/970

For that last one you have to expand the "Show evcc log output" branch to see it.

**Comment by timdorr** [comment]
I'm not familiar with that field specifically.

But if I'd have to guess, it's because you're not actually the primary account owner on the car? That is, someone at Tesla screwed up and you're actually a second owner without knowing it. 

I think you might have to reach out to Tesla, though I'd expect that to be pretty hard to resolve when you're dealing with a third-party app and something they've probably never heard of before. I mean, it's worth a shot, but I wouldn't put too much effort into it. Good luck, though!
