### ISSUE TITLE
Any update's documentation? 

### ISSUE THREAD

**Issue by Programistich** [timdorr/tesla-api#511]
I can't figure out which flow I should start using to use the API. There is an update in the Documentation header that some Tesla endpoint is closed, which gives you an access token. What is the right way to start using API now?

**Comment by timdorr** [comment]
The documentation is updated, just missing for MFA users. Check #374 for progress.

**Comment by Programistich** [comment]
That is, I can follow the steps on the site https://tesla-api.timdorr.com/api-basics/authentication?
