### ISSUE TITLE
login_hint parameter is breaking tesla APIs authorize

### ISSUE THREAD

**Issue by coletz** [timdorr/tesla-api#538]
Hi, I'm not totally sure about that, but it seems like providing the login_hint parameter (which is marked as optional in the documentation) the authorize webpage returns an error (https://auth.tesla.com/oauth2/v3/authorize).
It was working until 2 weeks ago, so I think they changed something since my app has not changed at all.
I would suggest you to try it and update the documentation removing the optional parameter if it is actually breaking something for everyone and not only for me

**Comment by tdorssers** [comment]
It looks like auth.tesla.cn is still accepting login_hint, but as soon as you get redirected to auth.tesla.com, the login_hint will cause a HTTP 500 error.

**Comment by saehyun** [comment]
same error - HTTP 500

**Comment by advaitkanthalia** [comment]
Bumping this up. 
Starting Thur, Mar 17, `login_hint` parameter is accepted by tesla. 

Sample : 
https://auth.tesla.com/oauth2/v3/authorize?client_id=ownerapi&code_challenge=123&code_challenge_method=S256&redirect_uri=https%3A%2F%2Fauth.tesla.com%2Fvoid%2Fcallback&response_type=code&scope=openid%20email%20offline_access&state=123&login_hint=adasdada%40yahoo.com

**Comment by coletz** [comment]
Can confirm, my old app started working again
