### ISSUE TITLE
DOC update

### ISSUE THREAD

**Issue by Panda88CO** [timdorr/tesla-api#550]
sun_roof_percent_open": 0,
"sun_roof_state": "closed",
are part of 'vehicel_state' not separate as shown in Data page

**Comment by timdorr** [comment]
Can you make a PR? Thanks!

**Comment by Panda88CO** [comment]
It is actually ok – just minor formatting issue Sent from Mail for Windows From: Tim DorrSent: Friday, March 25, 2022 9:42 PMTo: timdorr/tesla-apiCc: Panda88CO; AuthorSubject: Re: [timdorr/tesla-api] DOC update (Issue #550) Closed #550.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
