### ISSUE TITLE
Dog Mode and Camp Mode Endpoints

### ISSUE THREAD

**Issue by Megabytemb** [timdorr/tesla-api#568]
As of Mobile App version 4.7, you can now enable Camp mode and Dog mode.

Any chance we can figure out what the commands are for these new features?

**Comment by GaPhi** [comment]
Post {
    "command": "command/set_climate_keeper_mode",
    "qs": {},
    "body": {
        "climate_keeper_mode": 2
    }
}

Use :
0 for off
1 for on
2 for dog
3 for camp


Le mer. 27 avr. 2022 à 04:24, megabytemb ***@***.***> a
écrit :

**Comment by Megabytemb** [comment]
Thanks!!

**Comment by rawmean** [comment]
I get a 404 error. The authentication passes and I supply a correct v3 token. 
What am I doing wrong? Thanks!
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/1287087/169672560-d3f379c8-cda1-49a0-b5e6-0aac1d89025f.png">

**Comment by Megabytemb** [comment]
Pretty sure you need to use json in postman, not form encoded
