### ISSUE TITLE
Cabin Overheat Protection API Body

### ISSUE THREAD

**Issue by Megabytemb** [timdorr/tesla-api#571]
Hello,

Does anyone know what the Body params and Values are for the `SET_CABIN_OVERHEAT_PROTECTION` endpoint

URL is `api/1/vehicles/{vehicle_id}/command/set_cabin_overheat_protection` but I can't find anything about what values to set in the body.

**Comment by GaPhi** [comment]
{"command":"command/set_cabin_overheat_protection","qs":{},"body":{"on":false,"fan_only":false}}

Quite self explicit

Le mer. 4 mai 2022 à 14:44, Michael Benz ***@***.***> a
écrit :

**Comment by Megabytemb** [comment]
Works Beautifully. Thankyou
