### ISSUE TITLE
Failing at bearer token exchange to access token.

### ISSUE THREAD

**Issue by core-hacked** [timdorr/tesla-api#573]
When sending out the request I get:
```json
{
    "response": "unsupported_authentication_method_-_please_update_to_the_latest_version"
}
```
as a response from the API. I am using postman as way to get the token, however it leads to the error above.
What can I do to fix this?

**Comment by core-hacked** [comment]
Please update the documentation to fit this change, the API doesnt use this anymore, it uses the bearer token from step 3.

**Comment by core-hacked** [comment]
Addressed in [#574](https://github.com/timdorr/tesla-api/pull/574).

**Comment by jasminsehic** [comment]
@core-hacked can you by any chance provide any extra detail on what specifically you did to overcome this `unsupported_authentication_method_-_please_update_to_the_latest_version` response error you were getting? You mention using bearer token from step 3 but I am not following

**Comment by IMgoRt** [comment]
> @core-hacked can you by any chance provide any extra detail on what specifically you did to overcome this `unsupported_authentication_method_-_please_update_to_the_latest_version` response error you were getting? You mention using bearer token from step 3 but I am not following

The access token created in step 3 is now valid for 8 hours and is used for authentication.
The refresh token from step 3 is used to refresh every 8 hours

**Comment by jasminsehic** [comment]
Thanks @IMgoRt.
In my situation when the access token expires after 8 hours I get a 401 response and know then that it is expired I then use the refresh token to generate a new access token but I still then get the `unsupported_authentication_method_-_please_update_to_the_latest_version` response error, which is strange.

**Comment by jasminsehic** [comment]
That was very clear @core-hacked, thank you very much.
