### ISSUE TITLE
Software update schedule not working

### ISSUE THREAD

**Issue by fschaal** [timdorr/tesla-api#576]
I was playing around with the `schedule_software_update` endpoint and I notices that even if you provide an offset it still goes ahead and schedules the update as if I would send 0 as the offset. So basically install now.

When I scheduled the update from the car's interface it did work correctly. Is anyone else experiencing this?

**Comment by GaPhi** [comment]
Works perfectly here with offset in seconds. I use it with 120 for 2
minutes delay.

Le lun. 9 mai 2022 à 07:50, Florian Schaal ***@***.***> a
écrit :

**Comment by fschaal** [comment]
@GaPhi, 120 always seems to work because if you install now it always gives you a 2min window to cancel. Does it also work for you if you set it for 2h in advance? For me `scheduled_time_ms` is just now when I schedule it.

**Comment by core-hacked** [comment]
@fschaal 
1. Try with a POST Body and JSON. 
    > Tesla seems to favor this approach, going as far as depracting the use of post parameters.
2. Isn't the parameter supposed to be `offset_sec` for the `schedule_software_update` endpoint, otherwise [the documentation](https://github.com/timdorr/tesla-api/blob/master/docs/vehicle/commands/softwareupdate.md) needs to be updated. 

Kind Regards!

**Comment by GaPhi** [comment]
Yes, you're right : "offset_sec" is posted. (offset is the argument's name
used by TeslaJS library)

**Comment by fschaal** [comment]
@core-hacked, `offset_sec ` is correct. I've tried it both ways in my testing. First as post body and second as a query param. bother result in the same behaviour. 

Let me share an example.

URL:
`https://owner-api.teslamotors.com/api/1/vehicles/{vehicle_id}/command/schedule_software_update`

Body:
```json
{
    "offset_sec": "7200"
}
```
Response:
```json
{
    "response": {
        "expected_duration_sec": 1500,
        "reason": "",
        "result": true,
        "scheduled_time_ms": 1652244793992,
        "status": "scheduled",
        "warning_time_remaining_ms": 120000
    }
}
```
If I understand the endpoint correctly this request should schedule the installation in about 2 hours. 

- If we look at the request I get a `warning_time_remaining_ms` as if I requested the update to be installed now. 
- If we look at `scheduled_time_ms` this should be the time that the install will take place. So 2 hours from the request time. If I convert the epoch to an iso date it's almost the same as the request date-time `11/05/2022, 06:53:13`.

**Comment by fschaal** [comment]
@core-hacked, I've gone ahead and tried multiple combinations but with the same result. I do find it strange that the current Tesla app does not allow to schedule an update. Could be they just scrapped this for the mobile api.

**Comment by fschaal** [comment]
@core-hacked, could not agree more. I'm currently running 2022.4.5.18 so that should be absolutely fine in terms of API support.

**Comment by timdorr** [comment]
This should have been a discussion, but it's too late to convert now :D (everyone's comment becomes an "answer")

Let's keep the discussion about the API itself not working in a discussion. If we need to update the docs or library, that warrants an issue.
