### ISSUE TITLE
Further seat cooler documentation needed

### ISSUE THREAD

**Issue by itsMeDavidV** [timdorr/tesla-api#593]
Recently `command/remote_seat_cooler_request`  &  `"has_seat_cooling": Bool` have been added which are nice additions, but without knowing the state of each individual cooler, implementing a remote seat cooling feature would lead to an incomplete experience..

Has anyone found any info on seat cooler values or seen new variable names associated with them? If so can we get this info documented?

I'd check myself, but Santa hasn't blessed me with an s/x yet 😅

**Comment by timdorr** [comment]
Those are in the "data" APIs, which give you the overall state data on the car. If you have one with the heaters, you'll get that back in the response.

**Comment by itsMeDavidV** [comment]
@timdorr Yeah I'm aware, but was hoping someone could point to the specific variable names for the seat coolers as they're not in the example "data" response and I don't have cooled seats.
