### ISSUE TITLE
Tesla is continuously making changes to latest_vehicle_data

### ISSUE THREAD

**Issue by joexn** [timdorr/tesla-api#619]
Noticed this myself yesterday and seems this article covers the changes:

https://teslaupdates.org/article?news=374cfd6e-27f4-11ed-8950-f23c93ccce76

Looks like they're gearing up to actually store/cache car data?

**Comment by timdorr** [comment]
This doesn't have any realistic effect on the documentation. In fact, I think the author of that article may be confused, as the vehicle_data endpoint's content is determined by the car's computer, including what model it is, configuration it has, and software version is running. It can constantly change as new software updates are made or Tesla flips on/off feature flags in the mothership.

**Comment by joexn** [comment]
> This doesn't have any realistic effect on the documentation. In fact, I think the author of that article may be confused, as the vehicle_data endpoint's content is determined by the car's computer, including what model it is, configuration it has, and software version is running. It can constantly change as new software updates are made or Tesla flips on/off feature flags in the mothership.

I've tested this on my vehicle and the `latest_vehicle_data` has changed and I haven't had any updates for two weeks but it changed around a week ago. So you're saying this has changed on the car without any updates?

**Comment by timdorr** [comment]
Yes, they also have a feature flag system that can turn on/off features in the car remotely. Think Autopilot or EAP, but with much more minor things.
