### ISSUE TITLE
Heated Seats Auto Setting

### ISSUE THREAD

**Issue by InTheDaylight14** [timdorr/tesla-api#646]
Newer option in the Tesla app to set the front heated seats to 'Auto". The API uses level 0-3, not sure what it would use for Auto.

**Comment by alandtse** [comment]
I suspect it's a client only setting.

**Comment by InTheDaylight14** [comment]
https://tesla-api.timdorr.com/vehicle/commands/climate#post-api-1-vehicles-vehicle_id-command-remote_auto_seat_climate_request

Available in the climate_state:
```auto_seat_climate_left: false,
auto_seat_climate_right: true```

I assume that only the front seats can be put into auto climate. This is consistent with the Tesla mobile App.
