### ISSUE TITLE
Wiper blade heater command API call

### ISSUE THREAD

**Issue by theater** [timdorr/tesla-api#658]
Hi,
I used your unofficial documentation as a reference for some changes in OpenHAB Tesla integration. Great job and thanks for doing it!
I was wondering if you have any clue what is the proper API call for setting on/off the wiper blade heater on Model 3/Y (probably also on S and X)?
Is there a way how I can reverse engieer it and help find it so we can add it here as well?

Best regards,
Konstantin

**Comment by timdorr** [comment]
These appear to be tied to the defrost setting, so you would use the same API call for that: https://tesla-api.timdorr.com/vehicle/commands/climate#post-api-1-vehicles-id-command-set_preconditioning_max

**Comment by theater** [comment]
Oh. That's possible but in the car I have this as a separate option. Thanks!
