### ISSUE TITLE
Tesla Model S mileage

### ISSUE THREAD

**Issue by JakobBaranowski** [timdorr/tesla-api#66]
Hi there, 

I was wondering if there is a code to get the mileage of my tesla? 

I am trying to control my trips with the JSON API.

**Comment by alexhouse** [comment]
You can get the current odometer reading from the Vehicle State endpoint:

https://timdorr.docs.apiary.io/#reference/vehicles/state-and-settings/vehicle-state

The response contains: ```"odometer": 2171.454021,```
