### ISSUE TITLE
Fart Command

### ISSUE THREAD

**Issue by Urkman** [timdorr/tesla-api#668]
Is there already a known endpoint for the new Fart command?

**Comment by core-hacked** [comment]
> Is there already a known endpoint for the new Fart command?

The remote boombox? documented in PR #666 ?

**Comment by core-hacked** [comment]
@Urkman Try to request it. 

``POST /api/1/vehicles/{id}/command/remote_boombox``

I  will further document it then if it works.

**Comment by virtzilla** [comment]
> @Urkman may need a body parameter as json. It usually tells you the name of it in the response.
> 
> Example:
> 
> ```json
> {
>     "command": "fart"
> }
> ```

In this case from my experimentation POST'ing to the endpoint with an empty body results in the vehicle farting (seemingly picking at random from the option).

Response returned:
```
{"response":{"result":true,"reason":""}}
```

**Comment by Urkman** [comment]
So, with an empty body the fart is triggered?

**Comment by core-hacked** [comment]
Seems so. I will update the docs
