### ISSUE TITLE
Authentication User Agent

### ISSUE THREAD

**Issue by amirhmk** [timdorr/tesla-api#678]
Hi there, 

I have been using your documenation (thanks a lot!) and it works great! However, I've recently started having issues with token generation, and get the following error after trying to obtain a token using the `/token` endpoint. I have tried playing around with the `UA` and `X-Tesla-User-Agent` but doesn't seem to work. Any ideas? 

```
{'response': 'unsupported_authentication_method_-_please_update_to_the_latest_version'}
```

Note: it actually seems random, it works for some users, but doesn't for others...

**Comment by timdorr** [comment]
There is a new SSO authentication system. Please re-read the docs, as they have been updated for it.
