### ISSUE TITLE
Re: Login Issue

### ISSUE THREAD

**Issue by itsMeDavidV** [timdorr/tesla-api#690]
Seems there was a widespread change to login, recently. Watchla's sign in is down as well as Watchla users are reporting to me **that they cannot sign into many of their other Tesla API related services & platforms** (unrelated to Watchla). I have gotten many reports of this in the last few hours.

My personal error response after sc 400: 
`{"error":"invalid_request","error_description":"Invalid code_verifier","error_uri":"https://auth.tesla.com/error/reference/7c7a9289-bc30-45b7-aaf8-772d28432dd6-1676483903896"}`

I'm just now learning about this, but seems right to report as an issue.

**Comment by timdorr** [comment]
#689

**Comment by itsMeDavidV** [comment]
**FYI** for anyone looking into this, as of today 64 character `code_verifier` strings are no longer supported, only 86.

**Comment by timdorr** [comment]
Just so you know, [this is how I documented it](https://github.com/timdorr/tesla-api/blob/4bf2302d035056a235a3217f8fb82e2538249ab8/docs/api-basics/authentication.md?plain=1#L17) 😉
