### ISSUE TITLE
Tesla Oauth 2.0 api changed

### ISSUE THREAD

**Issue by mrgaolei** [timdorr/tesla-api#691]
From 2023-2-15, I found OAuth API changed, 
When I POST 'https://auth.tesla.cn/oauth2/v3/token'
return:
```json
 {"error":"invalid_request","error_description":"Invalid code_verifier","error_uri":"https://auth.tesla.cn
/error/reference/6a57805b-4b6f-419b-be7b-316f722214a0-1676528054175"}
```

Who know what changes?

**Comment by brianflex** [comment]
This is being discussed here:  https://github.com/timdorr/tesla-api/discussions/689
No answers yet, but maybe someone will discover something soon.

**Comment by timdorr** [comment]
#690

Make sure your `code_verifier` is exactly 86 characters.

**Comment by lyxlk** [comment]
Look this

**Comment by lyxlk** [comment]
Look this

**Comment by lyxlk** [comment]
//Look this         
        $len            = 43;
        $code_verifier  = CUtil::createVerifyCode($len,1);//[0-9A-Z]
        $code_challenge = base64_encode(hash('sha256',$code_verifier,true));//update info
        $code_challenge = str_replace(['+','/','='],['-','_',''],$code_challenge);

**Comment by lyxlk** [comment]
//You can try it ...

$len = 43;
$code_verifier = CUtil::createVerifyCode($len,1);//[0-9A-Z]
$code_challenge = base64_encode(hash('sha256',$code_verifier,true));//update info
$code_challenge = str_replace(['+','/','='],['-','_',''],$code_challenge);
