### ISSUE TITLE
API for MyQ garage door

### ISSUE THREAD

**Issue by theearthwanderer** [timdorr/tesla-api#697]
Hello, similar to Homelink, is there an API to trigger connected myQ garage door?

I understand I could probably use some other services to trigger myQ, but it seems that triggering through Tesla does not produce the 10 second beeping sound before closing. I wonder we could explore this API. Thank you

**Comment by timdorr** [comment]
There is already an API for this. While it's called `trigger_homelink`, it is agnostic about what system is running underneath: https://tesla-api.timdorr.com/vehicle/commands/homelink
