### ISSUE TITLE
[ruby] Login broken - You don't have permission to access to https://auth.tesla.com/oauth2/v3/authorize on this server

### ISSUE THREAD

**Issue by drnic** [timdorr/tesla-api#704]
I'm aware of https://github.com/timdorr/tesla-api/discussions/689 and there is some discussion of a fix to the ruby lib, but that fix didn't work for me.

When I run:

```ruby
  tesla_api = TeslaApi::Client.new(email: email)
  tesla_api.login!(password)
```

The [`sso_api.post("authorize?", ...`](https://github.com/timdorr/tesla-api/blob/910814963f72aad6faaa315ad4e18875bd11d68e/lib/tesla_api/client.rb#L88-L103) POST is returning 403 and the response HTML includes the error "You don't have permission to access to https://auth.tesla.com/oauth2/v3/authorize on this server"

Is this the same issue as #689 from earlier in the year; anyone else using the ruby lib getting the same thing or has a fix?

[I'm using HEAD from this repo]

**Comment by timdorr** [comment]
This is likely related to #431. I'm going to close this out to focus discussion there.
