### ISSUE TITLE
The vehicle option_codes is missing

### ISSUE THREAD

**Issue by ih000** [timdorr/tesla-api#708]
Recently, I found the api **/api/1/vehicles/xxx/vehicle_data** don't return the vehicle option_codes in field **vehicle_config**,  maybe it's little difficult to judge the vehicle is std, long range, or performance

**Comment by timdorr** [comment]
They've been moving away from the option_codes for years. They've been the same content for newer cars and the app has been using other API data for UI elements. It's been best to pull that data from other fields and endpoints for a while now. But we can get rid of it from the example response.
