### ISSUE TITLE
Is Apple removing Tesla third party apps?

### ISSUE THREAD

**Issue by Urkman** [timdorr/tesla-api#764]
My last Update was rejected for being a CopyCat.
Is this something new?

Is this by a push of Tesla?

<img width="612" alt="Bildschirmfoto 2023-10-30 um 20 34 58" src="https://github.com/timdorr/tesla-api/assets/94297/73274b47-c877-474f-9319-f5ef17c193db">

Any one else having this problems?

**Comment by timdorr** [comment]
This isn't something any outside company can influence with Apple. And it's certainly not something we can resolve here.
