### ISSUE TITLE
Climate not possible with low soc

### ISSUE THREAD

**Issue by Urkman** [timdorr/tesla-api#770]
When I use the "auto_conditioning_start" endpoint, but the battery is below 20% it returns false and the error "low_soc".
Is there a way to still turn I on and ignore this message?

**Comment by core-hacked** [comment]
Nope, that's a Tesla limit to preserve battery. You can't do it from the app either

**Comment by GaPhi** [comment]
Just add the following body request :

{
  "manual_override": "socdoors"
}

Should still be added to documentation...
