### ISSUE TITLE
Error Handling and Retry Mechanism for API Timeouts

### ISSUE THREAD

**Issue by pgsohail** [timdorr/tesla-api#787]
While using pyPowerwall to poll data from the Tesla Powerwall Gateway, I encountered frequent timeouts, especially when polling the /api/meters/aggregates and /api/system_status/soe endpoints. The current implementation does not handle these timeouts effectively, leading to failed API calls and incomplete data retrieval.

**Comment by timdorr** [comment]
This isn't the repo for that library.
