### ISSUE TITLE
Additional headers now required

### ISSUE THREAD

**Issue by matthew-pakulski** [timdorr/tesla-api#79]
As identified here:

https://teslamotorsclub.com/tmc/threads/error-in-tesla-api.127239/

Responses will now have a 503 error status code unless additional headers are added.

```
User-Agent: Mozilla/5.0 (Linux; Android 9.0.0; VS985 4G Build/LRX21Y; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/58.0.3029.83 Mobile Safari/537.36

X-Tesla-User-Agent: TeslaApp/3.4.4-350/fad4a582e/android/9.0.0
```

The values don't have to be these exactly, but the headers must exist. It'll probably help Tesla with their metrics actually if you supply your own values. For instance, my `X-Tesla-User-Agent` was set to `custom/ARC` and worked just fine.
Otherwise Tesla will think people are using old versions of their app.

As a reminder, you'll also want the following headers on all your POST requests, except of course the request for your authentication token which gives you the `${auth}` doesn't need the `authorization` header yet.
```
content-type: application/json
authorization: Bearer ${auth}
```

**Comment by mitchcapper** [comment]
UA is now required but X-Tesla-User-Agent is not (as far as I have seen).

**Comment by mrmorder** [comment]
I didn't test each one just saw that the app was passing both and added both in.

**Comment by jonasman** [comment]
are you sure these headers are required? i  authenticated just fine without them

**Comment by mitchcapper** [comment]
@jonasman  is it possible your client is setting a default UA if you don't?  I was unable to get it to work without specifying some UA instead getting back the supercharger  error.

**Comment by jonasman** [comment]
@mitchcapper nothing:

```
REQUEST: https://owner-api.teslamotors.com/oauth/token
METHOD: POST
Request Headers: [
"Content-Type": "application/json"
]
Request Body: {
  "client_id" : "e4a9949fcfa04068f59abb5a658f2bac0a3428e4652315490b659d5ab3f35a9e",
  "email" : "yyyyy",
  "password" : "xxxx",
  "client_secret" : "c75f14bbadc8bee3a7594412c31416f8300256d7668ea7e6e7f06727bfb9d220",
  "grant_type" : "password"
}

RESPONSE: Optional(https://owner-api.teslamotors.com/oauth/token)
StatusCode: 200
Headers: [
"Content-Type": "application/json"
]
Respose Body: {"access_token":"XXXXXXX","token_type":"bearer","expires_in":3888000,"refresh_token":"YYYYY","created_at":1536599091}

```

**Comment by jonasman** [comment]
```
REQUEST: https://owner-api.teslamotors.com/api/1/vehicles/XXXX/command/door_lock
METHOD: POST
Request Headers: [
"Authorization": "Bearer YYYYY"
]

RESPONSE: Optional(https://owner-api.teslamotors.com/api/1/vehicles/XXXX/command/door_lock)
StatusCode: 200
Headers: [
"Authorization": "Bearer YYYY"
]
Respose Body: {"response":{"reason":"","result":true}}

```

**Comment by mrmorder** [comment]
While it's possible... I just removed the user agent and it's still required. My guess is either your client is automatically adding a user agent which you'll have to see by using wireshark or fiddler or your account somehow doesn't require it.

**Comment by jonasman** [comment]
I vote for the last.
I tested my lib with another guy. Fir him it requires the user-agent while for me it does not.

Sent from my iPhone

On 16 Sep 2018, at 5.06, mrmorder <notifications@github.com<mailto:notifications@github.com>> wrote:


While it's possible... I just removed the user agent and it's still required. My guess is either your client is automatically adding a user agent which you'll have to see by using wireshark or fiddler or your account somehow doesn't require it.

**Comment by timdorr** [comment]
@jonasman What vehicles do you both have?

**Comment by mitchcapper** [comment]
@timdorr  M3 and new account for me required it.

**Comment by jonasman** [comment]
@timdorr you can follow our discussion here: https://github.com/jonasman/TeslaSwift/issues/21

We have: Model S, old MCU, 2018.32.4

**Comment by matthew-pakulski** [comment]
Model S 2015. Mine requires the User-Agent, and like others have pointed out, the `X-Tesla-User-Agent` wasn't necessary after all.

My `car_version` is "2018.34.1 3dd3072" and perhaps more importantly, the `api_version` is 3. Maybe it's an api version 2 vs version 3 change.

**Comment by mrmorder** [comment]
Model S/X 16/18. My guess is that there'll be a large api update anyway on the release of the version 9 update for S/X.

**Comment by jonasman** [comment]
@matthew-pakulski API version 3 here
