### ISSUE TITLE
Access Token refreshing

### ISSUE THREAD

**Issue by drewbaumann** [timdorr/tesla-api#83]
Hello. I looked through your library, and others, and have not been able to find documentation on refreshing an access token based on the refresh token. I was curious if this is something you looked into or if the best way to handle refreshing the access token is to simply grab a new one after expiration using the username and password. Thanks!

**Comment by bahree** [comment]
I tried it, when I was writing the [auth generator](http://desigeek.com/blog/amit/2018/08/06/windows-tesla-auth-token-generator/) but then could not find way to test it enough. Ended up going with creating a new one. You can check out the auth generator and the code on that link.

**Comment by drewbaumann** [comment]
@bahree Thanks for your response. I couldn't locate code on your site in regards to refreshing the access token based on the refresh token. Either way good stuff! I had fun looking at the API points you reverse engineered and will probably do something with that new navigation post call in the future.

**Comment by timdorr** [comment]
I'm fairly certain the `/oauth/token` endpoint accepts a refresh token grant as well: https://oauth.net/2/grant-types/refresh-token/

You would basically do `grant_type: refresh_token` and `refresh_token: $REFRESH_TOKEN` as parameters, removing the `email` and `password` params. I haven't tested it, but that would make sense if they're using the standard set of Ruby libraries for OAuth.

**Comment by drewbaumann** [comment]
@timdorr nice. I will give that a shot. If it works out I can add a PR.

**Comment by coreyward** [comment]
@drewbaumann Any news to report?

**Comment by haugene** [comment]
Can at least confirm that using the refresh token works according to the standard and as @timdorr describes. I'm working on my own integration with this API and is also implementing refreshing tokens these days (or soon). Request/response sequence below (and yes, the tokens are fake).

POST to https://owner-api.teslamotors.com/oauth/token
```
{
    "grant_type": "password",
    "client_id": "81527cff06843c8634fdc09e8ac0abefb46ac849f38fe1e431c2ef2106796384",
    "client_secret": "c7257eb71a564034f9419ee651c7d0e5f7aa6bfbd18bafb5c5c033b093bb2fa3",
    "email": "my@email.com",
    "password": "hunter2"
}
```
RESPONSE:
```
{
    "access_token": "ee4352c364cd1e78ed0a59734dd029d36910c455c8a0a5c14ef49546b18e99bf",
    "token_type": "bearer",
    "expires_in": 3888000,
    "refresh_token": "c09b05b7b18fe2a90fc8024abf19539aad4e67da0955ec9ab736b138c346855f",
    "created_at": 1541176299
}
```
And then new POST:
```
{
	"grant_type": "refresh_token",
	"client_id": "81527cff06843c8634fdc09e8ac0abefb46ac849f38fe1e431c2ef2106796384",
	"client_secret": "c7257eb71a564034f9419ee651c7d0e5f7aa6bfbd18bafb5c5c033b093bb2fa3",
	"refresh_token": "c09b05b7b18fe2a90fc8024abf19539aad4e67da0955ec9ab736b138c346855f"
}
```
RESPONSE:
```
{
    "access_token": "87428fc522803d31065e7bce3cf03fe475096631e5e07bbd7a0fde60c4cf25c7",
    "token_type": "bearer",
    "expires_in": 3888000,
    "refresh_token": "0263829989b6fd954f72baaf2fc64bc2e2f01d692d4de72986ea808f6e99813f",
    "created_at": 1541176370
}
```

And the second `access_token` works just fine on the different states and command APIs.

**Comment by drewbaumann** [comment]
@coreyward not by me, but it looks like @haugene proved that it works.

**Comment by timdorr** [comment]
Just added docs via #96!
