### ISSUE TITLE
Weird response from the endpoint. 

### ISSUE THREAD

**Issue by jbrass** [timdorr/tesla-api#86]
I am trying to run the sample code. I am getting the following error. I am able to reproduce this on both my mac and an ubuntu server.

`/root/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/json/common.rb:156:in 'parse': 822: unexpected token at '<html><head></head><body><p>Our servers are waiting for a supercharger spot..</p></body></html>' (JSON::ParserError)`

I have tried the example code with both the password method and token method. I am able to run the same operation in curl with the token and retrieve a list of vehicles in json. 

Initially i though this was some sort of rate limiting imposed by Tesla. I have also added the following options on TeslaApi::Client.vehicles **get** call:

`headers: {"User-Agent" => "ruby"},  debug_output: STDOUT`

Like from this [example]
(https://github.com/jnunemaker/httparty/blob/master/examples/headers_and_user_agents.rb) 

The debug_output shows the **tesla_api.vehicles** call getting a good response (with vehicle data) from the owners-api but the example code still throws the same "Our servers are waiting for a supercharger spot.." error. 

```
reading 604 bytes...
-> "{\"response\":[{\"id\":3122367xxxxx,\"vehicle_id\":4369xxx,\"vin\":\"5YJSA1Cxxxxx\",\"display_name\":\"Tessy\",\"option_codes\":\"AD02,AF00,AU00,BC0B,BP00,BR00,BS00,BT85,CH00,CW00,DA00,DRLH,DV2W,FG01,HP00,IDOM,IX00,LP00,PA00,PF00,PK01,PMMB,PS01,PX00,QPMT,RENA,RFPO,SC01,SP00,SU00,TM00,TP01,TR01,UTMF,WT19,WTX1,X001,X003,X007,X009,X011,X014,X021,X025,X027,X031,YF00,MDLS,COUS\",\"color\":null,\"tokens\":[\"xxx\",\"xxx\"],\"state\":\"asleep\",\"in_service\":false,\"id_s\":\"xxxx\",\"calendar_enabled\":true,\"api_version\":null,\"backseat_token\":null,\"backseat_token_updated_at\":null}],\"count\":1}"
```

**Comment by coreyward** [comment]
I'm getting this as well on [Tokens for Teslas](https://github.com/coreyward/tokens-for-teslas). Seems intermittent — I can build an API client and run `login!("password")` back to back and get different (successful vs this error) results. 

For what it's worth, I'm still on version 1.2.0 — `bundle update tesla_api` has no effect, even without a version locked (I'm assuming a newer version hasn't been pushed to Rubygems?).

**Comment by coreyward** [comment]
TMC has a little more info on a potential solution: https://teslamotorsclub.com/tmc/threads/error-in-tesla-api.127239/

**Comment by timdorr** [comment]
I haven't yet published a version with the User-Agent header.

**Comment by coreyward** [comment]
@timdorr Is there a reason for withholding a release? Seems this is increasingly becoming a problem for downstream users (👋 ) without that piece in place.

**Comment by timdorr** [comment]
OK, it's out!
