### ISSUE TITLE
Unlock and remote drive model 3

### ISSUE THREAD

**Issue by jonasman** [timdorr/tesla-api#95]
Hei guys,

Some users of my app are reporting a failure when unlocking and remote starting the car.
I dont have a model 3 to test. Can some one test and let me know if the API has change recently?

**Comment by matthew-pakulski** [comment]
I just tried to lock/unlock the Model 3 and got an error. You may get an error if the car is asleep. Try waking the car first.

[/api/1/vehicles/id/wake_up](https://tesla-api.timdorr.com/vehicle/commands/wake)
Look for this in the response: 
```json
{
  "response": {
    "state": "asleep"
  }
}
```
Repeat until you see: 
` "state": "online" `

The model 3 is narcoleptic.

**Comment by timdorr** [comment]
Do you have Always Connected checked? That might help you bypass the error.

Regardless, I don't think this is an issue with our docs.

**Comment by jonasman** [comment]
Hm interesting.

I will try the wake up command to see if it helps the users.


João

Sent from my iPhone

On 11 Dec 2018, at 22.15, Tim Dorr <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you have Always Connected checked? That might help you bypass the error.

Regardless, I don't think this is an issue with our docs.
